/*
 * Redfish API
 *
 * This contains the definition of a Redfish service.
 *
 * API version: 2018.3
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// The Drive schema represents a single physical disk drive for a system, including links to associated Volumes.
type Drive struct {
	// The OData description of a payload.
	OdataContext string `json:"@odata.context,omitempty"`
	// The current ETag of the resource.
	OdataEtag string `json:"@odata.etag,omitempty"`
	// The unique identifier for a resource.
	OdataId string `json:"@odata.id"`
	// The type of a resource.
	OdataType string `json:"@odata.type"`
	Actions Actions2 `json:"Actions,omitempty"`
	Assembly IdRef `json:"Assembly,omitempty"`
	// The user assigned asset tag for this drive.
	AssetTag string `json:"AssetTag,omitempty"`
	// The size of the smallest addressible unit (Block) of this drive in bytes.
	BlockSizeBytes int32 `json:"BlockSizeBytes,omitempty"`
	// The speed which this drive can communicate to a storage controller in ideal conditions in Gigabits per second.
	CapableSpeedGbs float32 `json:"CapableSpeedGbs,omitempty"`
	// The size in bytes of this Drive.
	CapacityBytes int32 `json:"CapacityBytes,omitempty"`
	// Provides a description of this resource and is used for commonality  in the schema definitions.
	Description string `json:"Description,omitempty"`
	EncryptionAbility EncryptionAbility `json:"EncryptionAbility,omitempty"`
	EncryptionStatus EncryptionStatus `json:"EncryptionStatus,omitempty"`
	// Is this drive currently predicting a failure in the near future.
	FailurePredicted bool `json:"FailurePredicted,omitempty"`
	HotspareReplacementMode HotspareReplacementModeType `json:"HotspareReplacementMode,omitempty"`
	HotspareType HotspareType `json:"HotspareType,omitempty"`
	// Uniquely identifies the resource within the collection of like resources.
	Id string `json:"Id"`
	// The Durable names for the drive.
	Identifiers []Identifier2 `json:"Identifiers,omitempty"`
	IndicatorLED IndicatorLed2 `json:"IndicatorLED,omitempty"`
	Links Links2 `json:"Links,omitempty"`
	// The Location of the drive.
	Location []Location `json:"Location,omitempty"`
	// This is the manufacturer of this drive.
	Manufacturer string `json:"Manufacturer,omitempty"`
	MediaType MediaType `json:"MediaType,omitempty"`
	// This is the model number for the drive.
	Model string `json:"Model,omitempty"`
	// The name of the resource or array element.
	Name string `json:"Name"`
	// The speed which this drive is currently communicating to the storage controller in Gigabits per second.
	NegotiatedSpeedGbs float32 `json:"NegotiatedSpeedGbs,omitempty"`
	Oem string `json:"Oem,omitempty"`
	// The operations currently running on the Drive.
	Operations []Operations `json:"Operations,omitempty"`
	// The part number for this drive.
	PartNumber string `json:"PartNumber,omitempty"`
	PhysicalLocation Location `json:"PhysicalLocation,omitempty"`
	// The percentage of reads and writes that are predicted to still be available for the media.
	PredictedMediaLifeLeftPercent float32 `json:"PredictedMediaLifeLeftPercent,omitempty"`
	Protocol IdRef `json:"Protocol,omitempty"`
	// The revision of this Drive. This is typically the firmware/hardware version of the drive.
	Revision string `json:"Revision,omitempty"`
	// The rotation speed of this Drive in Revolutions per Minute (RPM).
	RotationSpeedRPM float32 `json:"RotationSpeedRPM,omitempty"`
	// This is the SKU for this drive.
	SKU string `json:"SKU,omitempty"`
	// The serial number for this drive.
	SerialNumber string `json:"SerialNumber,omitempty"`
	Status Status `json:"Status,omitempty"`
	StatusIndicator StatusIndicator `json:"StatusIndicator,omitempty"`
}
