/*
 * Redfish API
 *
 * This contains the definition of a Redfish service.
 *
 * API version: 2018.3
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// Alarm trip information about the memory.  These alarms are reset when the system resets.  Note that if they are re-discovered they can be reasserted.
type AlarmTrips struct {
	// Address parity error detected status.
	AddressParityError bool `json:"AddressParityError,omitempty"`
	// Correctable data error threshold crossing alarm trip detected status.
	CorrectableECCError bool `json:"CorrectableECCError,omitempty"`
	// Spare block capacity crossing alarm trip detected status.
	SpareBlock bool `json:"SpareBlock,omitempty"`
	// Temperature threshold crossing alarm trip detected status.
	Temperature bool `json:"Temperature,omitempty"`
	// Uncorrectable data error threshold crossing alarm trip detected status.
	UncorrectableECCError bool `json:"UncorrectableECCError,omitempty"`
}
