/*
 * Redfish API
 *
 * This contains the definition of a Redfish service.
 *
 * API version: 2018.3
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
type PortConnectionType string

// List of PortConnectionType
const (
	PortConnectionTypeNOT_CONNECTED PortConnectionType = "NotConnected"
	PortConnectionTypeN_PORT PortConnectionType = "NPort"
	PortConnectionTypePOINT_TO_POINT PortConnectionType = "PointToPoint"
	PortConnectionTypePRIVATE_LOOP PortConnectionType = "PrivateLoop"
	PortConnectionTypePUBLIC_LOOP PortConnectionType = "PublicLoop"
	PortConnectionTypeGENERIC PortConnectionType = "Generic"
	PortConnectionTypeEXTENDER_FABRIC PortConnectionType = "ExtenderFabric"
)