/*
 * Redfish API
 *
 * This contains the definition of a Redfish service.
 *
 * API version: 2018.3
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// Single-Root Input/Output Virtualization (SR-IOV) capabilities.
type Sriov struct {
	// Whether this controller supports Single Root Input/Output Virtualization (SR-IOV) in Virtual Ethernet Port Aggregator (VEPA) mode.
	SRIOVVEPACapable bool `json:"SRIOVVEPACapable,omitempty"`
}
