/*
 * Redfish API
 *
 * This contains the definition of a Redfish service.
 *
 * API version: 2018.3
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
type SensorType string

// List of SensorType
const (
	SensorTypePLATFORM_SECURITY_VIOLATION_ATTEMPT SensorType = "Platform Security Violation Attempt"
	SensorTypeTEMPERATURE SensorType = "Temperature"
	SensorTypeVOLTAGE SensorType = "Voltage"
	SensorTypeCURRENT SensorType = "Current"
	SensorTypeFAN SensorType = "Fan"
	SensorTypePHYSICAL_CHASSIS_SECURITY SensorType = "Physical Chassis Security"
	SensorTypePROCESSOR SensorType = "Processor"
	SensorTypePOWER_SUPPLY__CONVERTER SensorType = "Power Supply / Converter"
	SensorTypePOWER_UNIT SensorType = "PowerUnit"
	SensorTypeCOOLING_DEVICE SensorType = "CoolingDevice"
	SensorTypeOTHER_UNITS_BASED_SENSOR SensorType = "Other Units-based Sensor"
	SensorTypeMEMORY SensorType = "Memory"
	SensorTypeDRIVE_SLOTBAY SensorType = "Drive Slot/Bay"
	SensorTypePOST_MEMORY_RESIZE SensorType = "POST Memory Resize"
	SensorTypeSYSTEM_FIRMWARE_PROGRESS SensorType = "System Firmware Progress"
	SensorTypeEVENT_LOGGING_DISABLED SensorType = "Event Logging Disabled"
	SensorTypeSYSTEM_EVENT SensorType = "System Event"
	SensorTypeCRITICAL_INTERRUPT SensorType = "Critical Interrupt"
	SensorTypeBUTTONSWITCH SensorType = "Button/Switch"
	SensorTypeMODULEBOARD SensorType = "Module/Board"
	SensorTypeMICROCONTROLLERCOPROCESSOR SensorType = "Microcontroller/Coprocessor"
	SensorTypeADD_IN_CARD SensorType = "Add-in Card"
	SensorTypeCHASSIS SensorType = "Chassis"
	SensorTypeCHIP_SET SensorType = "ChipSet"
	SensorTypeOTHER_FRU SensorType = "Other FRU"
	SensorTypeCABLEINTERCONNECT SensorType = "Cable/Interconnect"
	SensorTypeTERMINATOR SensorType = "Terminator"
	SensorTypeSYSTEM_BOOTRESTART SensorType = "SystemBoot/Restart"
	SensorTypeBOOT_ERROR SensorType = "Boot Error"
	SensorTypeBASE_OS_BOOTINSTALLATION_STATUS SensorType = "BaseOSBoot/InstallationStatus"
	SensorTypeOS_STOPSHUTDOWN SensorType = "OS Stop/Shutdown"
	SensorTypeSLOTCONNECTOR SensorType = "Slot/Connector"
	SensorTypeSYSTEM_ACPI_POWER_STATE SensorType = "System ACPI PowerState"
	SensorTypeWATCHDOG SensorType = "Watchdog"
	SensorTypePLATFORM_ALERT SensorType = "Platform Alert"
	SensorTypeENTITY_PRESENCE SensorType = "Entity Presence"
	SensorTypeMONITOR_ASICIC SensorType = "Monitor ASIC/IC"
	SensorTypeLAN SensorType = "LAN"
	SensorTypeMANAGEMENT_SUBSYSTEM_HEALTH SensorType = "Management Subsystem Health"
	SensorTypeBATTERY SensorType = "Battery"
	SensorTypeSESSION_AUDIT SensorType = "Session Audit"
	SensorTypeVERSION_CHANGE SensorType = "Version Change"
	SensorTypeFRU_STATE SensorType = "FRUState"
	SensorTypeOEM SensorType = "OEM"
)