/*
 * Redfish API
 *
 * This contains the definition of a Redfish service.
 *
 * API version: 2018.3
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
import (
	"time"
)

// This resource represents the log service for the resource or service to which it is associated.
type LogService struct {
	// The OData description of a payload.
	OdataContext string `json:"@odata.context,omitempty"`
	// The current ETag of the resource.
	OdataEtag string `json:"@odata.etag,omitempty"`
	// The unique identifier for a resource.
	OdataId string `json:"@odata.id"`
	// The type of a resource.
	OdataType string `json:"@odata.type"`
	Actions Actions2 `json:"Actions,omitempty"`
	// The current DateTime (with offset) for the log service, used to set or read time.
	DateTime time.Time `json:"DateTime,omitempty"`
	// The time offset from UTC that the DateTime property is set to in format: +06:00 .
	DateTimeLocalOffset string `json:"DateTimeLocalOffset,omitempty"`
	// Provides a description of this resource and is used for commonality  in the schema definitions.
	Description string `json:"Description,omitempty"`
	Entries IdRef `json:"Entries,omitempty"`
	// Uniquely identifies the resource within the collection of like resources.
	Id string `json:"Id"`
	LogEntryType LogEntryTypes `json:"LogEntryType,omitempty"`
	// The maximum number of log entries this service can have.
	MaxNumberOfRecords int32 `json:"MaxNumberOfRecords,omitempty"`
	// The name of the resource or array element.
	Name string `json:"Name"`
	Oem Oem `json:"Oem,omitempty"`
	OverWritePolicy OverWritePolicy `json:"OverWritePolicy,omitempty"`
	// This indicates whether this service is enabled.
	ServiceEnabled bool `json:"ServiceEnabled,omitempty"`
	Status Status `json:"Status,omitempty"`
}
