/*
 * Redfish API
 *
 * This contains the definition of a Redfish service.
 *
 * API version: 2018.3
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// A set of metrics that are collected into a metric report.
type MetricReportDefinition2 struct {
	// The OData description of a payload.
	OdataContext string `json:"@odata.context,omitempty"`
	// The current ETag of the resource.
	OdataEtag string `json:"@odata.etag,omitempty"`
	// The unique identifier for a resource.
	OdataId string `json:"@odata.id"`
	// The type of a resource.
	OdataType string `json:"@odata.type"`
	Actions Actions2 `json:"Actions,omitempty"`
	// Indicates the maximum number of entries that can be appended to a metric report.  When the metric report reaches its limit, its behavior is dictated by the ReportUpdates property.
	AppendLimit int32 `json:"AppendLimit,omitempty"`
	// Provides a description of this resource and is used for commonality  in the schema definitions.
	Description string `json:"Description,omitempty"`
	// Uniquely identifies the resource within the collection of like resources.
	Id string `json:"Id"`
	// Specifies a list of metric properties to include in the metric report.
	MetricProperties []string `json:"MetricProperties,omitempty"`
	MetricReport IdRef `json:"MetricReport,omitempty"`
	MetricReportDefinitionType MetricReportDefinitionType `json:"MetricReportDefinitionType,omitempty"`
	// Specifies a list of metrics to include in the metric report.  The metrics may include metric properties or calculations applied to a metric property.
	Metrics []Metric `json:"Metrics,omitempty"`
	// The name of the resource or array element.
	Name string `json:"Name"`
	Oem Oem `json:"Oem,omitempty"`
	// Specifies the actions to perform when a metric report is generated.
	ReportActions []ReportActionsEnum `json:"ReportActions,omitempty"`
	ReportUpdates ReportUpdatesEnum `json:"ReportUpdates,omitempty"`
	Schedule IdRef `json:"Schedule,omitempty"`
	Status Status `json:"Status,omitempty"`
	// Specifies the strings used to replace wildcards in the paths in MetricProperties array property.
	Wildcards []Wildcard `json:"Wildcards,omitempty"`
}
