/*
 * Redfish API
 *
 * This contains the definition of a Redfish service.
 *
 * API version: 2018.3
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
type AuthenticationMethod string

// List of AuthenticationMethod
const (
	AuthenticationMethodNONE AuthenticationMethod = "None"
	AuthenticationMethodCHAP AuthenticationMethod = "CHAP"
	AuthenticationMethodMUTUAL_CHAP AuthenticationMethod = "MutualCHAP"
)