/*
 * Redfish API
 *
 * This contains the definition of a Redfish service.
 *
 * API version: 2018.3
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
type RaidType string

// List of RAIDType
const (
	RaidTypeRAID0 RaidType = "RAID0"
	RaidTypeRAID1 RaidType = "RAID1"
	RaidTypeRAID3 RaidType = "RAID3"
	RaidTypeRAID4 RaidType = "RAID4"
	RaidTypeRAID5 RaidType = "RAID5"
	RaidTypeRAID6 RaidType = "RAID6"
	RaidTypeRAID10 RaidType = "RAID10"
	RaidTypeRAID01 RaidType = "RAID01"
	RaidTypeRAID6_TP RaidType = "RAID6TP"
	RaidTypeRAID1_E RaidType = "RAID1E"
	RaidTypeRAID50 RaidType = "RAID50"
	RaidTypeRAID60 RaidType = "RAID60"
	RaidTypeRAID00 RaidType = "RAID00"
	RaidTypeRAID10_E RaidType = "RAID10E"
	RaidTypeRAID1_TRIPLE RaidType = "RAID1Triple"
	RaidTypeRAID10_TRIPLE RaidType = "RAID10Triple"
)