/*
 * Redfish API
 *
 * This contains the definition of a Redfish service.
 *
 * API version: 2018.3
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
type CertificateType string

// List of CertificateType
const (
	CertificateTypePEM CertificateType = "PEM"
	CertificateTypePKCS7 CertificateType = "PKCS7"
)