/*
 * Redfish API
 *
 * This contains the definition of a Redfish service.
 *
 * API version: 2018.3
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
type SecurityStates string

// List of SecurityStates
const (
	SecurityStatesENABLED SecurityStates = "Enabled"
	SecurityStatesDISABLED SecurityStates = "Disabled"
	SecurityStatesUNLOCKED SecurityStates = "Unlocked"
	SecurityStatesLOCKED SecurityStates = "Locked"
	SecurityStatesFROZEN SecurityStates = "Frozen"
	SecurityStatesPASSPHRASELIMIT SecurityStates = "Passphraselimit"
)