/*
 * Redfish API
 *
 * This contains the definition of a Redfish service.
 *
 * API version: 2018.3
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// This schema defines a single Host Interface resource.
type HostInterface struct {
	// The OData description of a payload.
	OdataContext string `json:"@odata.context,omitempty"`
	// The current ETag of the resource.
	OdataEtag string `json:"@odata.etag,omitempty"`
	// The unique identifier for a resource.
	OdataId string `json:"@odata.id"`
	// The type of a resource.
	OdataType string `json:"@odata.type"`
	Actions Actions2 `json:"Actions,omitempty"`
	// The Role used when no authentication on this interface is used.
	AuthNoneRoleId string `json:"AuthNoneRoleId,omitempty"`
	// Indicates the authentication modes available on this interface.
	AuthenticationModes []AuthenticationMode `json:"AuthenticationModes,omitempty"`
	// Provides a description of this resource and is used for commonality  in the schema definitions.
	Description string `json:"Description,omitempty"`
	// Indicates whether this interface is accessible by external entities.
	ExternallyAccessible bool `json:"ExternallyAccessible,omitempty"`
	// Indicates whether this firmware authentication is enabled for this interface.
	FirmwareAuthEnabled bool `json:"FirmwareAuthEnabled,omitempty"`
	// The Role used for firmware authentication on this interface.
	FirmwareAuthRoleId string `json:"FirmwareAuthRoleId,omitempty"`
	HostEthernetInterfaces IdRef `json:"HostEthernetInterfaces,omitempty"`
	HostInterfaceType HostInterfaceType `json:"HostInterfaceType,omitempty"`
	// Uniquely identifies the resource within the collection of like resources.
	Id string `json:"Id"`
	// Indicates whether this interface is enabled.
	InterfaceEnabled bool `json:"InterfaceEnabled,omitempty"`
	// Indicates whether this kernel authentication is enabled for this interface.
	KernelAuthEnabled bool `json:"KernelAuthEnabled,omitempty"`
	// The Role used for kernel authentication on this interface.
	KernelAuthRoleId string `json:"KernelAuthRoleId,omitempty"`
	Links Links2 `json:"Links,omitempty"`
	ManagerEthernetInterface IdRef `json:"ManagerEthernetInterface,omitempty"`
	// The name of the resource or array element.
	Name string `json:"Name"`
	NetworkProtocol IdRef `json:"NetworkProtocol,omitempty"`
	Oem string `json:"Oem,omitempty"`
	Status Status `json:"Status,omitempty"`
}
