/*
 * Redfish API
 *
 * This contains the definition of a Redfish service.
 *
 * API version: 2018.3
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// Contains references to other resources that are related to this resource.
type StorageControllerLinks struct {
	// An array of references to the endpoints that connect to this controller.
	Endpoints []IdRef `json:"Endpoints,omitempty"`
	// The number of items in a collection.
	EndpointsodataCount int32 `json:"Endpoints@odata.count,omitempty"`
	Oem Oem `json:"Oem,omitempty"`
	// An array of references to the StorageServices that connect to this controller.
	StorageServices []IdRef `json:"StorageServices,omitempty"`
	// The number of items in a collection.
	StorageServicesodataCount int32 `json:"StorageServices@odata.count,omitempty"`
}
