/*
 * Redfish API
 *
 * This contains the definition of a Redfish service.
 *
 * API version: 2018.3
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// This object represents the root Redfish service.
type ServiceRoot struct {
	// The OData description of a payload.
	OdataContext string `json:"@odata.context,omitempty"`
	// The current ETag of the resource.
	OdataEtag string `json:"@odata.etag,omitempty"`
	// The unique identifier for a resource.
	OdataId string `json:"@odata.id"`
	// The type of a resource.
	OdataType string `json:"@odata.type"`
	AccountService IdRef `json:"AccountService,omitempty"`
	CertificateService IdRef `json:"CertificateService,omitempty"`
	Chassis IdRef `json:"Chassis,omitempty"`
	CompositionService IdRef `json:"CompositionService,omitempty"`
	// Provides a description of this resource and is used for commonality  in the schema definitions.
	Description string `json:"Description,omitempty"`
	EventService IdRef `json:"EventService,omitempty"`
	Fabrics IdRef `json:"Fabrics,omitempty"`
	// Uniquely identifies the resource within the collection of like resources.
	Id string `json:"Id"`
	JobService IdRef `json:"JobService,omitempty"`
	JsonSchemas IdRef `json:"JsonSchemas,omitempty"`
	Links Links `json:"Links"`
	Managers IdRef `json:"Managers,omitempty"`
	// The name of the resource or array element.
	Name string `json:"Name"`
	Oem Oem `json:"Oem,omitempty"`
	// The product associated with this Redfish service.
	Product string `json:"Product,omitempty"`
	ProtocolFeaturesSupported ProtocolFeaturesSupported `json:"ProtocolFeaturesSupported,omitempty"`
	// The version of the Redfish service.
	RedfishVersion string `json:"RedfishVersion,omitempty"`
	Registries IdRef `json:"Registries,omitempty"`
	ResourceBlocks IdRef `json:"ResourceBlocks,omitempty"`
	SessionService IdRef `json:"SessionService,omitempty"`
	StorageServices IdRef `json:"StorageServices,omitempty"`
	StorageSystems IdRef `json:"StorageSystems,omitempty"`
	Systems IdRef `json:"Systems,omitempty"`
	Tasks IdRef `json:"Tasks,omitempty"`
	TelemetryService IdRef `json:"TelemetryService,omitempty"`
	UUID string `json:"UUID,omitempty"`
	UpdateService IdRef `json:"UpdateService,omitempty"`
	// The vendor or manufacturer associated with this Redfish service.
	Vendor string `json:"Vendor,omitempty"`
}
