/*
 * Redfish API
 *
 * This contains the definition of a Redfish service.
 *
 * API version: 2018.3
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
type LocalAccountAuth string

// List of LocalAccountAuth
const (
	LocalAccountAuthENABLED LocalAccountAuth = "Enabled"
	LocalAccountAuthDISABLED LocalAccountAuth = "Disabled"
	LocalAccountAuthFALLBACK LocalAccountAuth = "Fallback"
)