/*
 * Redfish API
 *
 * This contains the definition of a Redfish service.
 *
 * API version: 2018.3
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// Contains a list of wildcards and their substitution values.
type Wildcard struct {
	// The name of Wildcard.
	Name string `json:"Name,omitempty"`
	// An array of values to substitute for the wildcard.
	Values []string `json:"Values,omitempty"`
}
