/*
 * Redfish API
 *
 * This contains the definition of a Redfish service.
 *
 * API version: 2018.3
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"time"
)

// This is the schema definition for a Manager.  Examples of managers are BMCs, Enclosure Managers, Management Controllers and other subsystems assigned managability functions.
type Manager struct {
	// The OData description of a payload.
	OdataContext string `json:"@odata.context,omitempty"`
	// The current ETag of the resource.
	OdataEtag string `json:"@odata.etag,omitempty"`
	// The unique identifier for a resource.
	OdataId string `json:"@odata.id"`
	// The type of a resource.
	OdataType string   `json:"@odata.type"`
	Actions   Actions2 `json:"Actions,omitempty"`
	// Indicates whether the manager is configured for automatic DST adjustment.
	AutoDSTEnabled bool         `json:"AutoDSTEnabled,omitempty"`
	CommandShell   CommandShell `json:"CommandShell,omitempty"`
	// The current DateTime (with offset) for the manager, used to set or read time.
	DateTime time.Time `json:"DateTime,omitempty"`
	// The time offset from UTC that the DateTime property is set to in format: +06:00 .
	DateTimeLocalOffset string `json:"DateTimeLocalOffset,omitempty"`
	// Provides a description of this resource and is used for commonality  in the schema definitions.
	Description        string `json:"Description,omitempty"`
	EthernetInterfaces IdRef  `json:"EthernetInterfaces,omitempty"`
	// The firmware version of this Manager.
	FirmwareVersion  string           `json:"FirmwareVersion,omitempty"`
	GraphicalConsole GraphicalConsole `json:"GraphicalConsole,omitempty"`
	HostInterfaces   IdRef            `json:"HostInterfaces,omitempty"`
	// Uniquely identifies the resource within the collection of like resources.
	Id          string      `json:"Id"`
	Links       Links2      `json:"Links,omitempty"`
	LogServices IdRef       `json:"LogServices,omitempty"`
	ManagerType ManagerType `json:"ManagerType,omitempty"`
	// The model information of this Manager as defined by the manufacturer.
	Model string `json:"Model,omitempty"`
	// The name of the resource or array element.
	Name            string      `json:"Name"`
	NetworkProtocol IdRef       `json:"NetworkProtocol,omitempty"`
	Oem             string      `json:"Oem,omitempty"`
	PowerState      PowerState2 `json:"PowerState,omitempty"`
	// Redundancy information for the managers of this system.
	Redundancy []IdRef `json:"Redundancy,omitempty"`
	// The number of items in a collection.
	RedundancyodataCount int32 `json:"Redundancy@odata.count,omitempty"`
	RemoteAccountService IdRef `json:"RemoteAccountService,omitempty"`
	// This property contains the URI of the Redfish Service Root for the remote Manager represented by this resource.
	RemoteRedfishServiceUri string        `json:"RemoteRedfishServiceUri,omitempty"`
	SerialConsole           SerialConsole `json:"SerialConsole,omitempty"`
	SerialInterfaces        IdRef         `json:"SerialInterfaces,omitempty"`
	ServiceEntryPointUUID   string        `json:"ServiceEntryPointUUID,omitempty"`
	Status                  Status        `json:"Status,omitempty"`
	UUID                    string        `json:"UUID,omitempty"`
	VirtualMedia            IdRef         `json:"VirtualMedia,omitempty"`
}
