/*
 * Redfish API
 *
 * This contains the definition of a Redfish service.
 *
 * API version: 2018.3
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
type ImplementationType string

// List of ImplementationType
const (
	ImplementationTypePHYSICAL_SENSOR ImplementationType = "PhysicalSensor"
	ImplementationTypeCALCULATED ImplementationType = "Calculated"
	ImplementationTypeSYNTHESIZED ImplementationType = "Synthesized"
	ImplementationTypeDIGITAL_METER ImplementationType = "DigitalMeter"
)