/*
 * Redfish API
 *
 * This contains the definition of a Redfish service.
 *
 * API version: 2018.3
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
type SlotTypes string

// List of SlotTypes
const (
	SlotTypesFULL_LENGTH SlotTypes = "FullLength"
	SlotTypesHALF_LENGTH SlotTypes = "HalfLength"
	SlotTypesLOW_PROFILE SlotTypes = "LowProfile"
	SlotTypesMINI SlotTypes = "Mini"
	SlotTypesM2 SlotTypes = "M2"
	SlotTypesOEM SlotTypes = "OEM"
)