/*
 * Redfish API
 *
 * This contains the definition of a Redfish service.
 *
 * API version: 2018.3
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
type IntrusionSensorReArm string

// List of IntrusionSensorReArm
const (
	IntrusionSensorReArmMANUAL IntrusionSensorReArm = "Manual"
	IntrusionSensorReArmAUTOMATIC IntrusionSensorReArm = "Automatic"
)