/*
 * Redfish API
 *
 * This contains the definition of a Redfish service.
 *
 * API version: 2018.3
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// This schema defines a Resource Block resource.
type ResourceBlock struct {
	// The OData description of a payload.
	OdataContext string `json:"@odata.context,omitempty"`
	// The current ETag of the resource.
	OdataEtag string `json:"@odata.etag,omitempty"`
	// The unique identifier for a resource.
	OdataId string `json:"@odata.id"`
	// The type of a resource.
	OdataType string `json:"@odata.type"`
	Actions Actions2 `json:"Actions,omitempty"`
	CompositionStatus CompositionStatus `json:"CompositionStatus"`
	// An array of references to the Computer Systems available in this Resource Block.
	ComputerSystems []IdRef `json:"ComputerSystems,omitempty"`
	// The number of items in a collection.
	ComputerSystemsodataCount int32 `json:"ComputerSystems@odata.count,omitempty"`
	// Provides a description of this resource and is used for commonality  in the schema definitions.
	Description string `json:"Description,omitempty"`
	// An array of references to the Drives available in this Resource Block.
	Drives []IdRef `json:"Drives,omitempty"`
	// The number of items in a collection.
	DrivesodataCount int32 `json:"Drives@odata.count,omitempty"`
	// An array of references to the Ethernet Interfaces available in this Resource Block.
	EthernetInterfaces []IdRef `json:"EthernetInterfaces,omitempty"`
	// The number of items in a collection.
	EthernetInterfacesodataCount int32 `json:"EthernetInterfaces@odata.count,omitempty"`
	// Uniquely identifies the resource within the collection of like resources.
	Id string `json:"Id"`
	Links Links2 `json:"Links,omitempty"`
	// An array of references to the Memory available in this Resource Block.
	Memory []IdRef `json:"Memory,omitempty"`
	// The number of items in a collection.
	MemoryodataCount int32 `json:"Memory@odata.count,omitempty"`
	// The name of the resource or array element.
	Name string `json:"Name"`
	// An array of references to the Network Interfaces available in this Resource Block.
	NetworkInterfaces []IdRef `json:"NetworkInterfaces,omitempty"`
	// The number of items in a collection.
	NetworkInterfacesodataCount int32 `json:"NetworkInterfaces@odata.count,omitempty"`
	Oem Oem `json:"Oem,omitempty"`
	// An array of references to the Processors available in this Resource Block.
	Processors []IdRef `json:"Processors,omitempty"`
	// The number of items in a collection.
	ProcessorsodataCount int32 `json:"Processors@odata.count,omitempty"`
	// This property represents the types of resources available on this Resource Block.
	ResourceBlockType []ResourceBlockType `json:"ResourceBlockType"`
	// An array of references to the Simple Storage available in this Resource Block.
	SimpleStorage []IdRef `json:"SimpleStorage,omitempty"`
	// The number of items in a collection.
	SimpleStorageodataCount int32 `json:"SimpleStorage@odata.count,omitempty"`
	Status Status `json:"Status,omitempty"`
	// An array of references to the Storage available in this Resource Block.
	Storage []IdRef `json:"Storage,omitempty"`
	// The number of items in a collection.
	StorageodataCount int32 `json:"Storage@odata.count,omitempty"`
}
