/*
 * Redfish API
 *
 * This contains the definition of a Redfish service.
 *
 * API version: 2018.3
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
type PrivilegeType string

// List of PrivilegeType
const (
	PrivilegeTypeLOGIN PrivilegeType = "Login"
	PrivilegeTypeCONFIGURE_MANAGER PrivilegeType = "ConfigureManager"
	PrivilegeTypeCONFIGURE_USERS PrivilegeType = "ConfigureUsers"
	PrivilegeTypeCONFIGURE_SELF PrivilegeType = "ConfigureSelf"
	PrivilegeTypeCONFIGURE_COMPONENTS PrivilegeType = "ConfigureComponents"
)