/*
 * Redfish API
 *
 * This contains the definition of a Redfish service.
 *
 * API version: 2018.3
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// Contains a set of properties that indicate which properties are supported in the $filter query parameter for the ServerSentEventUri.
type SseFilterPropertiesSupported struct {
	// This indicates if the EventFormatType property is supported.
	EventFormatType bool `json:"EventFormatType,omitempty"`
	// This indicates if the EventType property is supported.
	EventType bool `json:"EventType,omitempty"`
	// This indicates if the MessageId property is supported.
	MessageId bool `json:"MessageId,omitempty"`
	// This indicates if the MetricReportDefinition property is supported.
	MetricReportDefinition bool `json:"MetricReportDefinition,omitempty"`
	// This indicates if the OriginResource property is supported.
	OriginResource bool `json:"OriginResource,omitempty"`
	// This indicates if the RegistryPrefix property is supported.
	RegistryPrefix bool `json:"RegistryPrefix,omitempty"`
	// This indicates if the ResourceType property is supported.
	ResourceType bool `json:"ResourceType,omitempty"`
}
