/*
 * Redfish API
 *
 * This contains the definition of a Redfish service.
 *
 * API version: 2018.3
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type AccountProviderTypes string

// List of AccountProviderTypes
const (
	AccountProviderTypesREDFISH_SERVICE          AccountProviderTypes = "RedfishService"
	AccountProviderTypesACTIVE_DIRECTORY_SERVICE AccountProviderTypes = "ActiveDirectoryService"
	AccountProviderTypesLDAP_SERVICE             AccountProviderTypes = "LDAPService"
	AccountProviderTypesOEM                      AccountProviderTypes = "OEM"
)
