/*
 * Redfish API
 *
 * This contains the definition of a Redfish service.
 *
 * API version: 2018.3
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
type IndicatorLed string

// List of IndicatorLED
const (
	IndicatorLedUNKNOWN IndicatorLed = "Unknown"
	IndicatorLedLIT IndicatorLed = "Lit"
	IndicatorLedBLINKING IndicatorLed = "Blinking"
	IndicatorLedOFF IndicatorLed = "Off"
)