/*
 * Redfish API
 *
 * This contains the definition of a Redfish service.
 *
 * API version: 2018.3
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
type ProcessorArchitecture string

// List of ProcessorArchitecture
const (
	ProcessorArchitectureX86 ProcessorArchitecture = "x86"
	ProcessorArchitectureIA_64 ProcessorArchitecture = "IA-64"
	ProcessorArchitectureARM ProcessorArchitecture = "ARM"
	ProcessorArchitectureMIPS ProcessorArchitecture = "MIPS"
	ProcessorArchitecturePOWER ProcessorArchitecture = "Power"
	ProcessorArchitectureOEM ProcessorArchitecture = "OEM"
)