/*
 * Redfish API
 *
 * This contains the definition of a Redfish service.
 *
 * API version: 2018.3
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
type DataBits string

// List of DataBits
const (
	DataBits_5 DataBits = "5"
	DataBits_6 DataBits = "6"
	DataBits_7 DataBits = "7"
	DataBits_8 DataBits = "8"
)