/*
 * Redfish API
 *
 * This contains the definition of a Redfish service.
 *
 * API version: 2018.3
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// This schema defines a storage controller and its respective properties.  A storage controller represents a storage device (physical or virtual) that produces Volumes.
type StorageController struct {
	// The unique identifier for a resource.
	OdataId string `json:"@odata.id"`
	Actions StorageControllerActions `json:"Actions,omitempty"`
	Assembly IdRef `json:"Assembly,omitempty"`
	// The user assigned asset tag for this storage controller.
	AssetTag string `json:"AssetTag,omitempty"`
	CacheSummary CacheSummary `json:"CacheSummary,omitempty"`
	// The firmware version of this storage Controller.
	FirmwareVersion string `json:"FirmwareVersion,omitempty"`
	// The Durable names for the storage controller.
	Identifiers []Identifier2 `json:"Identifiers,omitempty"`
	Links StorageControllerLinks `json:"Links,omitempty"`
	Location Location `json:"Location,omitempty"`
	// This is the manufacturer of this storage controller.
	Manufacturer string `json:"Manufacturer,omitempty"`
	// This is the identifier for the member within the collection.
	MemberId string `json:"MemberId"`
	// This is the model number for the storage controller.
	Model string `json:"Model,omitempty"`
	// The name of the Storage Controller.
	Name string `json:"Name,omitempty"`
	Oem string `json:"Oem,omitempty"`
	PCIeInterface PcIeInterface `json:"PCIeInterface,omitempty"`
	// The part number for this storage controller.
	PartNumber string `json:"PartNumber,omitempty"`
	// This is the SKU for this storage controller.
	SKU string `json:"SKU,omitempty"`
	// The serial number for this storage controller.
	SerialNumber string `json:"SerialNumber,omitempty"`
	// The maximum speed of the storage controller's device interface.
	SpeedGbps float32 `json:"SpeedGbps,omitempty"`
	Status Status `json:"Status,omitempty"`
	// This represents the protocols by which this storage controller can be communicated to.
	SupportedControllerProtocols []IdRef `json:"SupportedControllerProtocols,omitempty"`
	// This represents the protocols which the storage controller can use to communicate with attached devices.
	SupportedDeviceProtocols []IdRef `json:"SupportedDeviceProtocols,omitempty"`
	// This object describes the RAID Types supported by the storage controller.
	SupportedRAIDTypes []RaidType `json:"SupportedRAIDTypes,omitempty"`
}
