/*
 * Redfish API
 *
 * This contains the definition of a Redfish service.
 *
 * API version: 2018.3
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
type EventFormatType string

// List of EventFormatType
const (
	EventFormatTypeEVENT EventFormatType = "Event"
	EventFormatTypeMETRIC_REPORT EventFormatType = "MetricReport"
)