/*
 * Redfish API
 *
 * This contains the definition of a Redfish service.
 *
 * API version: 2018.3
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// MetricDataType : The data type of the related metric values.  The property provides information to the client on the nature of the metric reading.
type MetricDataType string

// List of MetricDataType
const (
	MetricDataTypeBOOLEAN MetricDataType = "Boolean"
	MetricDataTypeDATE_TIME MetricDataType = "DateTime"
	MetricDataTypeDECIMAL MetricDataType = "Decimal"
	MetricDataTypeINTEGER MetricDataType = "Integer"
	MetricDataTypeSTRING MetricDataType = "String"
	MetricDataTypeENUMERATION MetricDataType = "Enumeration"
)