/*
 * Redfish API
 *
 * This contains the definition of a Redfish service.
 *
 * API version: 2018.3
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
type PowerState string

// List of PowerState
const (
	PowerStateON PowerState = "On"
	PowerStateOFF PowerState = "Off"
	PowerStatePOWERING_ON PowerState = "PoweringOn"
	PowerStatePOWERING_OFF PowerState = "PoweringOff"
)