/*
 * Redfish API
 *
 * This contains the definition of a Redfish service.
 *
 * API version: 2018.3
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// This type describes an input range for a power supply.
type InputRange struct {
	InputType InputType `json:"InputType,omitempty"`
	// The maximum line input frequency at which this power supply input range is effective.
	MaximumFrequencyHz float32 `json:"MaximumFrequencyHz,omitempty"`
	// The maximum line input voltage at which this power supply input range is effective.
	MaximumVoltage float32 `json:"MaximumVoltage,omitempty"`
	// The minimum line input frequency at which this power supply input range is effective.
	MinimumFrequencyHz float32 `json:"MinimumFrequencyHz,omitempty"`
	// The minimum line input voltage at which this power supply input range is effective.
	MinimumVoltage float32 `json:"MinimumVoltage,omitempty"`
	Oem Oem `json:"Oem,omitempty"`
	// The maximum capacity of this Power Supply when operating in this input range.
	OutputWattage float32 `json:"OutputWattage,omitempty"`
}
