/*
 * Redfish API
 *
 * This contains the definition of a Redfish service.
 *
 * API version: 2018.3
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
type OperatingMemoryModes string

// List of OperatingMemoryModes
const (
	OperatingMemoryModesVOLATILE OperatingMemoryModes = "Volatile"
	OperatingMemoryModesPMEM OperatingMemoryModes = "PMEM"
	OperatingMemoryModesBLOCK OperatingMemoryModes = "Block"
)