/*
 * Redfish API
 *
 * This contains the definition of a Redfish service.
 *
 * API version: 2018.3
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type Location2 struct {
	// This indicates the location of the resource.
	Info string `json:"Info,omitempty"`
	// This represents the format of the Info property.
	InfoFormat string `json:"InfoFormat,omitempty"`
	Oem string `json:"Oem,omitempty"`
}
