/*
 * Redfish API
 *
 * This contains the definition of a Redfish service.
 *
 * API version: 2018.3
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
type MediaType string

// List of MediaType
const (
	MediaTypeHDD MediaType = "HDD"
	MediaTypeSSD MediaType = "SSD"
	MediaTypeSMR MediaType = "SMR"
)