/*
 * Redfish API
 *
 * This contains the definition of a Redfish service.
 *
 * API version: 2018.3
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
type FunctionType string

// List of FunctionType
const (
	FunctionTypePHYSICAL FunctionType = "Physical"
	FunctionTypeVIRTUAL FunctionType = "Virtual"
)