/*
 * Redfish API
 *
 * This contains the definition of a Redfish service.
 *
 * API version: 2018.3
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// This object describes services that may be running or installed on the system.
type HostedServices struct {
	Oem string `json:"Oem,omitempty"`
	StorageServices IdRef `json:"StorageServices,omitempty"`
}
