/*
 * Redfish API
 *
 * This contains the definition of a Redfish service.
 *
 * API version: 2018.3
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// Represents a remote resource that is connected to the network accessible to this endpoint.
type ConnectedEntity struct {
	EntityLink IdRef `json:"EntityLink,omitempty"`
	EntityPciId PciId `json:"EntityPciId,omitempty"`
	EntityRole EntityRole `json:"EntityRole,omitempty"`
	EntityType EntityType `json:"EntityType,omitempty"`
	// Identifiers for the remote entity.
	Identifiers []Identifier2 `json:"Identifiers,omitempty"`
	Oem Oem `json:"Oem,omitempty"`
	// The Class Code, Subclass code, and Programming Interface code of this PCIe function.
	PciClassCode string `json:"PciClassCode,omitempty"`
	// The PCI ID of the connected entity.
	PciFunctionNumber int32 `json:"PciFunctionNumber,omitempty"`
}
