/*
 * Redfish API
 *
 * This contains the definition of a Redfish service.
 *
 * API version: 2018.3
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// This is the schema definition of a Memory Domain and its configuration. Memory Domains are used to indicate to the client which Memory (DIMMs) can be grouped together in Memory Chunks to form interleave sets or otherwise grouped together.
type MemoryDomain struct {
	// The OData description of a payload.
	OdataContext string `json:"@odata.context,omitempty"`
	// The current ETag of the resource.
	OdataEtag string `json:"@odata.etag,omitempty"`
	// The unique identifier for a resource.
	OdataId string `json:"@odata.id"`
	// The type of a resource.
	OdataType string `json:"@odata.type"`
	Actions Actions2 `json:"Actions,omitempty"`
	// Indicates if this Memory Domain supports the provisioning of blocks of memory.
	AllowsBlockProvisioning bool `json:"AllowsBlockProvisioning,omitempty"`
	// Indicates if this Memory Domain supports the creation of Memory Chunks.
	AllowsMemoryChunkCreation bool `json:"AllowsMemoryChunkCreation,omitempty"`
	// Indicates if this Memory Domain supports the creation of Memory Chunks with mirroring enabled.
	AllowsMirroring bool `json:"AllowsMirroring,omitempty"`
	// Indicates if this Memory Domain supports the creation of Memory Chunks with sparing enabled.
	AllowsSparing bool `json:"AllowsSparing,omitempty"`
	// Provides a description of this resource and is used for commonality  in the schema definitions.
	Description string `json:"Description,omitempty"`
	// Uniquely identifies the resource within the collection of like resources.
	Id string `json:"Id"`
	// This is the interleave sets for the memory chunk.
	InterleavableMemorySets []MemorySet `json:"InterleavableMemorySets,omitempty"`
	MemoryChunks IdRef `json:"MemoryChunks,omitempty"`
	// The name of the resource or array element.
	Name string `json:"Name"`
	Oem string `json:"Oem,omitempty"`
}
