/*
 * Redfish API
 *
 * This contains the definition of a Redfish service.
 *
 * API version: 2018.3
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
type InterfaceType string

// List of InterfaceType
const (
	InterfaceTypeTPM1_2 InterfaceType = "TPM1_2"
	InterfaceTypeTPM2_0 InterfaceType = "TPM2_0"
	InterfaceTypeTCM1_0 InterfaceType = "TCM1_0"
)