/*
 * Redfish API
 *
 * This contains the definition of a Redfish service.
 *
 * API version: 2018.3
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// A remote service that can provide accounts for this manager to utilize for authentication.
type ExternalAccountProvider struct {
	AccountProviderType AccountProviderTypes `json:"AccountProviderType,omitempty"`
	Authentication Authentication `json:"Authentication,omitempty"`
	Certificates IdRef `json:"Certificates,omitempty"`
	LDAPService LdapService `json:"LDAPService,omitempty"`
	// This property contains a collection of the mapping rules to convert the external account providers account information to the local Redfish Role.
	RemoteRoleMapping []RoleMapping `json:"RemoteRoleMapping,omitempty"`
	// This property contains the addresses of the user account providers this resource references. The format of this field depends on the Type.
	ServiceAddresses []string `json:"ServiceAddresses,omitempty"`
	// This indicates whether this service is enabled.
	ServiceEnabled bool `json:"ServiceEnabled,omitempty"`
}
