/*
 * Redfish API
 *
 * This contains the definition of a Redfish service.
 *
 * API version: 2018.3
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// This type describe the power metrics for a resource.
type PowerMetric struct {
	// The average power level over the measurement window (the last IntervalInMin minutes).
	AverageConsumedWatts float32 `json:"AverageConsumedWatts,omitempty"`
	// The time interval (or window) in which the PowerMetrics are measured over.
	IntervalInMin int32 `json:"IntervalInMin,omitempty"`
	// The highest power consumption level that has occured over the measurement window (the last IntervalInMin minutes).
	MaxConsumedWatts float32 `json:"MaxConsumedWatts,omitempty"`
	// The lowest power consumption level over the measurement window (the last IntervalInMin minutes).
	MinConsumedWatts float32 `json:"MinConsumedWatts,omitempty"`
}
