/*
 * Redfish API
 *
 * This contains the definition of a Redfish service.
 *
 * API version: 2018.3
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
type PinOut string

// List of PinOut
const (
	PinOutCISCO PinOut = "Cisco"
	PinOutCYCLADES PinOut = "Cyclades"
	PinOutDIGI PinOut = "Digi"
)