/*
 * Redfish API
 *
 * This contains the definition of a Redfish service.
 *
 * API version: 2018.3
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// This action is used to generate a metric report.
type SubmitTestMetricReportRequestBody struct {
	// The content of the MetricReportValues in the generated metric report.
	GeneratedMetricReportValues []MetricValue `json:"GeneratedMetricReportValues"`
	// The Name property of the metric report in generated metric report.
	MetricReportName string `json:"MetricReportName"`
	// The content of MetricReportValues array in generated metric report.
	MetricReportValues string `json:"MetricReportValues,omitempty"`
}
