/*
 * Redfish API
 *
 * This contains the definition of a Redfish service.
 *
 * API version: 2018.3
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
type CalculationAlgorithmEnum string

// List of CalculationAlgorithmEnum
const (
	CalculationAlgorithmEnumAVERAGE CalculationAlgorithmEnum = "Average"
	CalculationAlgorithmEnumMAXIMUM CalculationAlgorithmEnum = "Maximum"
	CalculationAlgorithmEnumMINIMUM CalculationAlgorithmEnum = "Minimum"
)