/*
 * Redfish API
 *
 * This contains the definition of a Redfish service.
 *
 * API version: 2018.3
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// NIC Partitioning capability, status, and configuration for a controller.
type NicPartitioning struct {
	// Indicates whether or not NIC function partitioning is supported by a controller.
	NparCapable bool `json:"NparCapable,omitempty"`
	// When true, NIC function partitioning is active on this controller.
	NparEnabled bool `json:"NparEnabled,omitempty"`
}
