/*
 * Redfish API
 *
 * This contains the definition of a Redfish service.
 *
 * API version: 2018.3
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
type CommandConnectTypesSupported string

// List of CommandConnectTypesSupported
const (
	CommandConnectTypesSupportedSSH CommandConnectTypesSupported = "SSH"
	CommandConnectTypesSupportedTELNET CommandConnectTypesSupported = "Telnet"
	CommandConnectTypesSupportedIPMI CommandConnectTypesSupported = "IPMI"
	CommandConnectTypesSupportedOEM CommandConnectTypesSupported = "Oem"
)