/*
 * Redfish API
 *
 * This contains the definition of a Redfish service.
 *
 * API version: 2018.3
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// A remote service that can provide accounts for this manager to utilize for authentication.
type ExternalAccountProvider2 struct {
	// The unique identifier for a resource.
	OdataId string `json:"@odata.id,omitempty"`
}
