/*
 * Redfish API
 *
 * This contains the definition of a Redfish service.
 *
 * API version: 2018.3
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
type EntityType string

// List of EntityType
const (
	EntityTypeSTORAGE_INITIATOR EntityType = "StorageInitiator"
	EntityTypeROOT_COMPLEX EntityType = "RootComplex"
	EntityTypeNETWORK_CONTROLLER EntityType = "NetworkController"
	EntityTypeDRIVE EntityType = "Drive"
	EntityTypeSTORAGE_EXPANDER EntityType = "StorageExpander"
	EntityTypeDISPLAY_CONTROLLER EntityType = "DisplayController"
	EntityTypeBRIDGE EntityType = "Bridge"
	EntityTypePROCESSOR EntityType = "Processor"
	EntityTypeVOLUME EntityType = "Volume"
	EntityTypeACCELERATION_FUNCTION EntityType = "AccelerationFunction"
)