/*
 * Redfish API
 *
 * This contains the definition of a Redfish service.
 *
 * API version: 2018.3
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
type IntrusionSensor string

// List of IntrusionSensor
const (
	IntrusionSensorNORMAL IntrusionSensor = "Normal"
	IntrusionSensorHARDWARE_INTRUSION IntrusionSensor = "HardwareIntrusion"
	IntrusionSensorTAMPERING_DETECTED IntrusionSensor = "TamperingDetected"
)