/*
 * Redfish API
 *
 * This contains the definition of a Redfish service.
 *
 * API version: 2018.3
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// A Virtualization offload capability of a controller.
type VirtualizationOffload struct {
	SRIOV Sriov `json:"SRIOV,omitempty"`
	VirtualFunction VirtualFunction `json:"VirtualFunction,omitempty"`
}
