/*
 * Redfish API
 *
 * This contains the definition of a Redfish service.
 *
 * API version: 2018.3
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
type EventType string

// List of EventType
const (
	EventTypeSTATUS_CHANGE EventType = "StatusChange"
	EventTypeRESOURCE_UPDATED EventType = "ResourceUpdated"
	EventTypeRESOURCE_ADDED EventType = "ResourceAdded"
	EventTypeRESOURCE_REMOVED EventType = "ResourceRemoved"
	EventTypeALERT EventType = "Alert"
	EventTypeMETRIC_REPORT EventType = "MetricReport"
)