/*
 * Redfish API
 *
 * This contains the definition of a Redfish service.
 *
 * API version: 2018.3
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// This is the schema definition of a Memory Chunk and its configuration.
type MemoryChunks struct {
	// The unique identifier for a resource.
	OdataId string `json:"@odata.id,omitempty"`
	// The OData description of a payload.
	OdataContext string `json:"@odata.context,omitempty"`
	// The type of a resource.
	OdataType string `json:"@odata.type,omitempty"`
	AddressRangeType AddressRangeType `json:"AddressRangeType,omitempty"`
	// Provides a description of this resource and is used for commonality  in the schema definitions.
	Description string `json:"Description,omitempty"`
	// Uniquely identifies the resource within the collection of like resources.
	Id string `json:"Id"`
	// This is the interleave sets for the memory chunk.
	InterleaveSets []InterleaveSet `json:"InterleaveSets,omitempty"`
	// Mirror Enabled status
	IsMirrorEnabled bool `json:"IsMirrorEnabled,omitempty"`
	// Spare enabled status
	IsSpare bool `json:"IsSpare,omitempty"`
	// Size of the memory chunk in MiB
	MemoryChunkSizeMiB float32 `json:"MemoryChunkSizeMiB,omitempty"`
	// The name of the resource or array element.
	Name string `json:"Name"`
	Oem Oem `json:"Oem,omitempty"`
}
