/*
 * Redfish API
 *
 * This contains the definition of a Redfish service.
 *
 * API version: 2018.3
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// This action is used to change the BIOS passwords.
type ChangePasswordRequestBody struct {
	// The value of the new BIOS password.
	NewPassword string `json:"NewPassword"`
	// The value of the existing password.
	OldPassword string `json:"OldPassword"`
	// The name of the BIOS password to change.
	PasswordName string `json:"PasswordName"`
}
