/*
 * Redfish API
 *
 * This contains the definition of a Redfish service.
 *
 * API version: 2018.3
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
type PowerState2 string

// List of PowerState_2
const (
	PowerState2ON PowerState2 = "On"
	PowerState2OFF PowerState2 = "Off"
	PowerState2POWERING_ON PowerState2 = "PoweringOn"
	PowerState2POWERING_OFF PowerState2 = "PoweringOff"
)