/*
 * Redfish API
 *
 * This contains the definition of a Redfish service.
 *
 * API version: 2018.3
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// This is the schema definition for the PCIeDevice resource.  It represents the properties of a PCIeDevice attached to a System.
type PcIeDevice struct {
	// The OData description of a payload.
	OdataContext string `json:"@odata.context,omitempty"`
	// The current ETag of the resource.
	OdataEtag string `json:"@odata.etag,omitempty"`
	// The unique identifier for a resource.
	OdataId string `json:"@odata.id"`
	// The type of a resource.
	OdataType string `json:"@odata.type"`
	Actions Actions2 `json:"Actions,omitempty"`
	Assembly IdRef `json:"Assembly,omitempty"`
	// The user assigned asset tag for this PCIe device.
	AssetTag string `json:"AssetTag,omitempty"`
	// Provides a description of this resource and is used for commonality  in the schema definitions.
	Description string `json:"Description,omitempty"`
	DeviceType DeviceType `json:"DeviceType,omitempty"`
	// The version of firmware for this PCIe device.
	FirmwareVersion string `json:"FirmwareVersion,omitempty"`
	// Uniquely identifies the resource within the collection of like resources.
	Id string `json:"Id"`
	Links Links2 `json:"Links,omitempty"`
	// This is the manufacturer of this PCIe device.
	Manufacturer string `json:"Manufacturer,omitempty"`
	// This is the model number for the PCIe device.
	Model string `json:"Model,omitempty"`
	// The name of the resource or array element.
	Name string `json:"Name"`
	Oem Oem `json:"Oem,omitempty"`
	PCIeInterface PcIeInterface2 `json:"PCIeInterface,omitempty"`
	// The part number for this PCIe device.
	PartNumber string `json:"PartNumber,omitempty"`
	// This is the SKU for this PCIe device.
	SKU string `json:"SKU,omitempty"`
	// The serial number for this PCIe device.
	SerialNumber string `json:"SerialNumber,omitempty"`
	Status Status `json:"Status,omitempty"`
}
