/*
 * Redfish API
 *
 * This contains the definition of a Redfish service.
 *
 * API version: 2018.3
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// This sets the CurrentPeriod object values to zero.
type ClearCurrentPeriodRequestBody struct {
}
