/*
 * Redfish API
 *
 * This contains the definition of a Redfish service.
 *
 * API version: 2018.3
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
type Parity string

// List of Parity
const (
	ParityNONE Parity = "None"
	ParityEVEN Parity = "Even"
	ParityODD Parity = "Odd"
	ParityMARK Parity = "Mark"
	ParitySPACE Parity = "Space"
)