/*
 * Redfish API
 *
 * This contains the definition of a Redfish service.
 *
 * API version: 2018.3
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// This action is used to add a Resource Block to a system.
type AddResourceBlockRequestBody struct {
	// The current ETag of the system.
	ComputerSystemETag string `json:"ComputerSystemETag,omitempty"`
	ResourceBlock IdRef `json:"ResourceBlock"`
	// The current ETag of the Resource Block to add to the system.
	ResourceBlockETag string `json:"ResourceBlockETag,omitempty"`
}
