/*
 * Redfish API
 *
 * This contains the definition of a Redfish service.
 *
 * API version: 2018.3
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
type ManagerType string

// List of ManagerType
const (
	ManagerTypeMANAGEMENT_CONTROLLER ManagerType = "ManagementController"
	ManagerTypeENCLOSURE_MANAGER ManagerType = "EnclosureManager"
	ManagerTypeBMC ManagerType = "BMC"
	ManagerTypeRACK_MANAGER ManagerType = "RackManager"
	ManagerTypeAUXILIARY_CONTROLLER ManagerType = "AuxiliaryController"
	ManagerTypeSERVICE ManagerType = "Service"
)