/*
 * Redfish API
 *
 * This contains the definition of a Redfish service.
 *
 * API version: 2018.3
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
type MemoryDeviceType string

// List of MemoryDeviceType
const (
	MemoryDeviceTypeDDR MemoryDeviceType = "DDR"
	MemoryDeviceTypeDDR2 MemoryDeviceType = "DDR2"
	MemoryDeviceTypeDDR3 MemoryDeviceType = "DDR3"
	MemoryDeviceTypeDDR4 MemoryDeviceType = "DDR4"
	MemoryDeviceTypeDDR4_SDRAM MemoryDeviceType = "DDR4_SDRAM"
	MemoryDeviceTypeDDR4_E_SDRAM MemoryDeviceType = "DDR4E_SDRAM"
	MemoryDeviceTypeLPDDR4_SDRAM MemoryDeviceType = "LPDDR4_SDRAM"
	MemoryDeviceTypeDDR3_SDRAM MemoryDeviceType = "DDR3_SDRAM"
	MemoryDeviceTypeLPDDR3_SDRAM MemoryDeviceType = "LPDDR3_SDRAM"
	MemoryDeviceTypeDDR2_SDRAM MemoryDeviceType = "DDR2_SDRAM"
	MemoryDeviceTypeDDR2_SDRAM_FB_DIMM MemoryDeviceType = "DDR2_SDRAM_FB_DIMM"
	MemoryDeviceTypeDDR2_SDRAM_FB_DIMM_PROBE MemoryDeviceType = "DDR2_SDRAM_FB_DIMM_PROBE"
	MemoryDeviceTypeDDR_SGRAM MemoryDeviceType = "DDR_SGRAM"
	MemoryDeviceTypeDDR_SDRAM MemoryDeviceType = "DDR_SDRAM"
	MemoryDeviceTypeROM MemoryDeviceType = "ROM"
	MemoryDeviceTypeSDRAM MemoryDeviceType = "SDRAM"
	MemoryDeviceTypeEDO MemoryDeviceType = "EDO"
	MemoryDeviceTypeFAST_PAGE_MODE MemoryDeviceType = "FastPageMode"
	MemoryDeviceTypePIPELINED_NIBBLE MemoryDeviceType = "PipelinedNibble"
	MemoryDeviceTypeLOGICAL MemoryDeviceType = "Logical"
	MemoryDeviceTypeHBM MemoryDeviceType = "HBM"
	MemoryDeviceTypeHBM2 MemoryDeviceType = "HBM2"
)