/*
 * Redfish API
 *
 * This contains the definition of a Redfish service.
 *
 * API version: 2018.3
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
type WwnSource string

// List of WWNSource
const (
	WwnSourceCONFIGURED_LOCALLY WwnSource = "ConfiguredLocally"
	WwnSourcePROVIDED_BY_FABRIC WwnSource = "ProvidedByFabric"
)