/*
 * Redfish API
 *
 * This contains the definition of a Redfish service.
 *
 * API version: 2018.3
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
type AuthenticationMode string

// List of AuthenticationMode
const (
	AuthenticationModeAUTH_NONE AuthenticationMode = "AuthNone"
	AuthenticationModeBASIC_AUTH AuthenticationMode = "BasicAuth"
	AuthenticationModeREDFISH_SESSION_AUTH AuthenticationMode = "RedfishSessionAuth"
	AuthenticationModeOEM_AUTH AuthenticationMode = "OemAuth"
)