/*
 * Redfish API
 *
 * This contains the definition of a Redfish service.
 *
 * API version: 2018.3
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
type ResourceBlockType string

// List of ResourceBlockType
const (
	ResourceBlockTypeCOMPUTE ResourceBlockType = "Compute"
	ResourceBlockTypePROCESSOR ResourceBlockType = "Processor"
	ResourceBlockTypeMEMORY ResourceBlockType = "Memory"
	ResourceBlockTypeNETWORK ResourceBlockType = "Network"
	ResourceBlockTypeSTORAGE ResourceBlockType = "Storage"
	ResourceBlockTypeCOMPUTER_SYSTEM ResourceBlockType = "ComputerSystem"
	ResourceBlockTypeEXPANSION ResourceBlockType = "Expansion"
)