/*
 * Redfish API
 *
 * This contains the definition of a Redfish service.
 *
 * API version: 2018.3
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
type IndicatorLed2 string

// List of IndicatorLED_2
const (
	IndicatorLed2LIT IndicatorLed2 = "Lit"
	IndicatorLed2BLINKING IndicatorLed2 = "Blinking"
	IndicatorLed2OFF IndicatorLed2 = "Off"
)