/*
 * Redfish API
 *
 * This contains the definition of a Redfish service.
 *
 * API version: 2018.3
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// The available actions for this resource.
type TemperatureActions struct {
	Oem Oem `json:"Oem,omitempty"`
}
