/*
 * Redfish API
 *
 * This contains the definition of a Redfish service.
 *
 * API version: 2018.3
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
type AccelerationFunctionType string

// List of AccelerationFunctionType
const (
	AccelerationFunctionTypeENCRYPTION AccelerationFunctionType = "Encryption"
	AccelerationFunctionTypeCOMPRESSION AccelerationFunctionType = "Compression"
	AccelerationFunctionTypePACKET_INSPECTION AccelerationFunctionType = "PacketInspection"
	AccelerationFunctionTypePACKET_SWITCH AccelerationFunctionType = "PacketSwitch"
	AccelerationFunctionTypeSCHEDULER AccelerationFunctionType = "Scheduler"
	AccelerationFunctionTypeAUDIO_PROCESSING AccelerationFunctionType = "AudioProcessing"
	AccelerationFunctionTypeVIDEO_PROCESSING AccelerationFunctionType = "VideoProcessing"
	AccelerationFunctionTypeOEM AccelerationFunctionType = "OEM"
)