/*
 * Redfish API
 *
 * This contains the definition of a Redfish service.
 *
 * API version: 2018.3
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type PowerControl struct {
	// The unique identifier for a resource.
	OdataId string `json:"@odata.id"`
	Actions PowerControlActions `json:"Actions,omitempty"`
	// This is the identifier for the member within the collection.
	MemberId string `json:"MemberId"`
	// Power Control Function name.
	Name string `json:"Name,omitempty"`
	Oem Oem `json:"Oem,omitempty"`
	PhysicalContext IdRef `json:"PhysicalContext,omitempty"`
	// The total amount of power that has been allocated (or budegeted)to  chassis resources.
	PowerAllocatedWatts float32 `json:"PowerAllocatedWatts,omitempty"`
	// The amount of power not already budgeted and therefore available for additional allocation. (powerCapacity - powerAllocated).  This indicates how much reserve power capacity is left.
	PowerAvailableWatts float32 `json:"PowerAvailableWatts,omitempty"`
	// The total amount of power available to the chassis for allocation. This may the power supply capacity, or power budget assigned to the chassis from an up-stream chassis.
	PowerCapacityWatts float32 `json:"PowerCapacityWatts,omitempty"`
	// The actual power being consumed by the chassis.
	PowerConsumedWatts float32 `json:"PowerConsumedWatts,omitempty"`
	PowerLimit PowerLimit `json:"PowerLimit,omitempty"`
	PowerMetrics PowerMetric `json:"PowerMetrics,omitempty"`
	// The potential power that the chassis resources are requesting which may be higher than the current level being consumed since requested power includes budget that the chassis resource wants for future use.
	PowerRequestedWatts float32 `json:"PowerRequestedWatts,omitempty"`
	// The ID(s) of the resources associated with this Power Limit.
	RelatedItem []IdRef `json:"RelatedItem,omitempty"`
	// The number of items in a collection.
	RelatedItemodataCount int32 `json:"RelatedItem@odata.count,omitempty"`
	Status Status `json:"Status,omitempty"`
}
