/*
 * Redfish API
 *
 * This contains the definition of a Redfish service.
 *
 * API version: 2018.3
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// This object contains power limit status and configuration information for the chassis.
type PowerLimit struct {
	// The time required for the limiting process to reduce power consumption to below the limit.
	CorrectionInMs int32 `json:"CorrectionInMs,omitempty"`
	LimitException PowerLimitException `json:"LimitException,omitempty"`
	// The Power limit in watts. Set to null to disable power capping.
	LimitInWatts float32 `json:"LimitInWatts,omitempty"`
}
