/*
 * Redfish API
 *
 * This contains the definition of a Redfish service.
 *
 * API version: 2018.3
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
type IPv6AddressOrigin string

// List of IPv6AddressOrigin
const (
	IPv6AddressOriginSTATIC IPv6AddressOrigin = "Static"
	IPv6AddressOriginDHC_PV6 IPv6AddressOrigin = "DHCPv6"
	IPv6AddressOriginLINK_LOCAL IPv6AddressOrigin = "LinkLocal"
	IPv6AddressOriginSLAAC IPv6AddressOrigin = "SLAAC"
)