/*
 * Redfish API
 *
 * This contains the definition of a Redfish service.
 *
 * API version: 2018.3
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
type PcIeTypes string

// List of PCIeTypes
const (
	PcIeTypesGEN1 PcIeTypes = "Gen1"
	PcIeTypesGEN2 PcIeTypes = "Gen2"
	PcIeTypesGEN3 PcIeTypes = "Gen3"
	PcIeTypesGEN4 PcIeTypes = "Gen4"
	PcIeTypesGEN5 PcIeTypes = "Gen5"
)