/*
 * Redfish API
 *
 * This contains the definition of a Redfish service.
 *
 * API version: 2018.3
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
type LogEntryType string

// List of LogEntryType
const (
	LogEntryTypeEVENT LogEntryType = "Event"
	LogEntryTypeSEL LogEntryType = "SEL"
	LogEntryTypeOEM LogEntryType = "Oem"
)