/*
 * Redfish API
 *
 * This contains the definition of a Redfish service.
 *
 * API version: 2018.3
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// This type describes the FPGA reconfiguration slot.  A reconfiguration slot is used by an FPGA to contain an acceleration function that can change as the FPGA is being provisioned.
type FpgaReconfigurationSlot struct {
	AccelerationFunction IdRef `json:"AccelerationFunction,omitempty"`
	// This flag indicates if the reconfiguration slot can be reprogrammed from the host using system software.
	ProgrammableFromHost bool `json:"ProgrammableFromHost,omitempty"`
	// The FPGA reconfiguration slot identifier.
	SlotId string `json:"SlotId,omitempty"`
	UUID string `json:"UUID,omitempty"`
}
