/*
 * Redfish API
 *
 * This contains the definition of a Redfish service.
 *
 * API version: 2018.3
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// A PCI ID.
type PciId struct {
	// The Class Code, Subclass code, and Programming Interface code of this PCIe function.
	ClassCode string `json:"ClassCode,omitempty"`
	// The Device ID of this PCIe function.
	DeviceId string `json:"DeviceId,omitempty"`
	// The PCI ID of the connected entity.
	FunctionNumber int32 `json:"FunctionNumber,omitempty"`
	// The Subsystem ID of this PCIe function.
	SubsystemId string `json:"SubsystemId,omitempty"`
	// The Subsystem Vendor ID of this PCIe function.
	SubsystemVendorId string `json:"SubsystemVendorId,omitempty"`
	// The Vendor ID of this PCIe function.
	VendorId string `json:"VendorId,omitempty"`
}
