/*
 * Redfish API
 *
 * This contains the definition of a Redfish service.
 *
 * API version: 2018.3
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// InterfaceTypeSelection : The enumerations of InterfaceTypeSelection specify the method for switching the TrustedModule InterfaceType, for instance between TPM1_2 and TPM2_0, if supported.
type InterfaceTypeSelection string

// List of InterfaceTypeSelection
const (
	InterfaceTypeSelectionNONE InterfaceTypeSelection = "None"
	InterfaceTypeSelectionFIRMWARE_UPDATE InterfaceTypeSelection = "FirmwareUpdate"
	InterfaceTypeSelectionBIOS_SETTING InterfaceTypeSelection = "BiosSetting"
	InterfaceTypeSelectionOEM_METHOD InterfaceTypeSelection = "OemMethod"
)