/*
 * Redfish API
 *
 * This contains the definition of a Redfish service.
 *
 * API version: 2018.3
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
type ProcessorMemoryType string

// List of ProcessorMemoryType
const (
	ProcessorMemoryTypeL1_CACHE ProcessorMemoryType = "L1Cache"
	ProcessorMemoryTypeL2_CACHE ProcessorMemoryType = "L2Cache"
	ProcessorMemoryTypeL3_CACHE ProcessorMemoryType = "L3Cache"
	ProcessorMemoryTypeL4_CACHE ProcessorMemoryType = "L4Cache"
	ProcessorMemoryTypeL5_CACHE ProcessorMemoryType = "L5Cache"
	ProcessorMemoryTypeL6_CACHE ProcessorMemoryType = "L6Cache"
	ProcessorMemoryTypeL7_CACHE ProcessorMemoryType = "L7Cache"
	ProcessorMemoryTypeHBM1 ProcessorMemoryType = "HBM1"
	ProcessorMemoryTypeHBM2 ProcessorMemoryType = "HBM2"
	ProcessorMemoryTypeHBM3 ProcessorMemoryType = "HBM3"
	ProcessorMemoryTypeSGRAM ProcessorMemoryType = "SGRAM"
	ProcessorMemoryTypeGDDR ProcessorMemoryType = "GDDR"
	ProcessorMemoryTypeGDDR2 ProcessorMemoryType = "GDDR2"
	ProcessorMemoryTypeGDDR3 ProcessorMemoryType = "GDDR3"
	ProcessorMemoryTypeGDDR4 ProcessorMemoryType = "GDDR4"
	ProcessorMemoryTypeGDDR5 ProcessorMemoryType = "GDDR5"
	ProcessorMemoryTypeGDDR5_X ProcessorMemoryType = "GDDR5X"
	ProcessorMemoryTypeGDDR6 ProcessorMemoryType = "GDDR6"
	ProcessorMemoryTypeDDR ProcessorMemoryType = "DDR"
	ProcessorMemoryTypeDDR2 ProcessorMemoryType = "DDR2"
	ProcessorMemoryTypeDDR3 ProcessorMemoryType = "DDR3"
	ProcessorMemoryTypeDDR4 ProcessorMemoryType = "DDR4"
	ProcessorMemoryTypeDDR5 ProcessorMemoryType = "DDR5"
	ProcessorMemoryTypeSDRAM ProcessorMemoryType = "SDRAM"
	ProcessorMemoryTypeSRAM ProcessorMemoryType = "SRAM"
	ProcessorMemoryTypeFLASH ProcessorMemoryType = "Flash"
	ProcessorMemoryTypeOEM ProcessorMemoryType = "OEM"
)