/*
 * Redfish API
 *
 * This contains the definition of a Redfish service.
 *
 * API version: 2018.3
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
type FlowControl2 string

// List of FlowControl_2
const (
	FlowControl2NONE FlowControl2 = "None"
	FlowControl2SOFTWARE FlowControl2 = "Software"
	FlowControl2HARDWARE FlowControl2 = "Hardware"
)