/*
 * Redfish API
 *
 * This contains the definition of a Redfish service.
 *
 * API version: 2018.3
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
type EventSeverity string

// List of EventSeverity
const (
	EventSeverityOK EventSeverity = "OK"
	EventSeverityWARNING EventSeverity = "Warning"
	EventSeverityCRITICAL EventSeverity = "Critical"
)