/*
 * Redfish API
 *
 * This contains the definition of a Redfish service.
 *
 * API version: 2018.3
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type InterleaveSet struct {
	Memory IdRef2 `json:"Memory,omitempty"`
	// Level of the interleave set for multi-level tiered memory.
	MemoryLevel float32 `json:"MemoryLevel,omitempty"`
	// Offset within the DIMM that corresponds to the start of this memory region, with units in MiB
	OffsetMiB float32 `json:"OffsetMiB,omitempty"`
	// DIMM region identifier
	RegionId string `json:"RegionId,omitempty"`
	// Size of this memory region in MiB
	SizeMiB float32 `json:"SizeMiB,omitempty"`
}
