/*
 * Redfish API
 *
 * This contains the definition of a Redfish service.
 *
 * API version: 2018.3
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// Specifies a metric to include in the metric report. The metrics are derived by applying a calculation on each of the listed metric properties.
type Metric struct {
	// Specifies the duration over which the function is computed.
	CollectionDuration string `json:"CollectionDuration,omitempty"`
	CollectionFunction CalculationAlgorithmEnum2 `json:"CollectionFunction,omitempty"`
	CollectionTimeScope CollectionTimeScope `json:"CollectionTimeScope,omitempty"`
	// Specifies the label for the metric definition which is derived by applying the CollectionFunction to the metric property.
	MetricId string `json:"MetricId,omitempty"`
	// A collection of URI for the properties on which this metric is collected.
	MetricProperties []string `json:"MetricProperties,omitempty"`
}
