/*
 * Redfish API
 *
 * This contains the definition of a Redfish service.
 *
 * API version: 2018.3
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
type InputType string

// List of InputType
const (
	InputTypeAC InputType = "AC"
	InputTypeDC InputType = "DC"
)