/*
 * Redfish API
 *
 * This contains the definition of a Redfish service.
 *
 * API version: 2018.3
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
type VolumeType string

// List of VolumeType
const (
	VolumeTypeRAW_DEVICE VolumeType = "RawDevice"
	VolumeTypeNON_REDUNDANT VolumeType = "NonRedundant"
	VolumeTypeMIRRORED VolumeType = "Mirrored"
	VolumeTypeSTRIPED_WITH_PARITY VolumeType = "StripedWithParity"
	VolumeTypeSPANNED_MIRRORS VolumeType = "SpannedMirrors"
	VolumeTypeSPANNED_STRIPES_WITH_PARITY VolumeType = "SpannedStripesWithParity"
)