/*
 * Redfish API
 *
 * This contains the definition of a Redfish service.
 *
 * API version: 2018.3
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
type LinkNetworkTechnology string

// List of LinkNetworkTechnology
const (
	LinkNetworkTechnologyETHERNET LinkNetworkTechnology = "Ethernet"
	LinkNetworkTechnologyINFINI_BAND LinkNetworkTechnology = "InfiniBand"
	LinkNetworkTechnologyFIBRE_CHANNEL LinkNetworkTechnology = "FibreChannel"
)