/*
 * Redfish API
 *
 * This contains the definition of a Redfish service.
 *
 * API version: 2018.3
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
type EntityRole string

// List of EntityRole
const (
	EntityRoleINITIATOR EntityRole = "Initiator"
	EntityRoleTARGET EntityRole = "Target"
	EntityRoleBOTH EntityRole = "Both"
)