/*
 * Redfish API
 *
 * This contains the definition of a Redfish service.
 *
 * API version: 2018.3
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
type OverWritePolicy2 string

// List of OverWritePolicy_2
const (
	OverWritePolicy2MANUAL OverWritePolicy2 = "Manual"
	OverWritePolicy2OLDEST OverWritePolicy2 = "Oldest"
)