/*
 * Redfish API
 *
 * This contains the definition of a Redfish service.
 *
 * API version: 2018.3
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
type AuthenticationTypes string

// List of AuthenticationTypes
const (
	AuthenticationTypesTOKEN AuthenticationTypes = "Token"
	AuthenticationTypesKERBEROS_KEYTAB AuthenticationTypes = "KerberosKeytab"
	AuthenticationTypesUSERNAME_AND_PASSWORD AuthenticationTypes = "UsernameAndPassword"
	AuthenticationTypesOEM AuthenticationTypes = "OEM"
)