/*
 * Redfish API
 *
 * This contains the definition of a Redfish service.
 *
 * API version: 2018.3
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
type HostInterfaceType string

// List of HostInterfaceType
const (
	HostInterfaceTypeNETWORK_HOST_INTERFACE HostInterfaceType = "NetworkHostInterface"
)