/*
 * Redfish API
 *
 * This contains the definition of a Redfish service.
 *
 * API version: 2018.3
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// A entry in the RFC 6724 Address Selection Policy Table.
type IPv6AddressPolicyEntry struct {
	// The IPv6 Label (as defined in RFC 6724 section 2.1).
	Label int32 `json:"Label,omitempty"`
	// The IPv6 Precedence (as defined in RFC 6724 section 2.1.
	Precedence int32 `json:"Precedence,omitempty"`
	// The IPv6 Address Prefix (as defined in RFC 6724 section 2.1).
	Prefix string `json:"Prefix,omitempty"`
}
