/*
 * Redfish API
 *
 * This contains the definition of a Redfish service.
 *
 * API version: 2018.3
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// The ModifyRedundancySet operation is used to add or remove members to a redundant group of manager.
type ModifyRedundancySetRequestBody struct {
	// This array defines the Managers to add to the redundancy set.  In this case, a valid reference is supported.
	Add []IdRef `json:"Add,omitempty"`
	// This array defines the Managers to remove from the redundancy set.  In this case, a valid reference is supported.
	Remove []IdRef `json:"Remove,omitempty"`
}
