/*
 * Redfish API
 *
 * This contains the definition of a Redfish service.
 *
 * API version: 2018.3
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
type ResetType string

// List of ResetType
const (
	ResetTypeON ResetType = "On"
	ResetTypeFORCE_OFF ResetType = "ForceOff"
	ResetTypeGRACEFUL_SHUTDOWN ResetType = "GracefulShutdown"
	ResetTypeGRACEFUL_RESTART ResetType = "GracefulRestart"
	ResetTypeFORCE_RESTART ResetType = "ForceRestart"
	ResetTypeNMI ResetType = "Nmi"
	ResetTypeFORCE_ON ResetType = "ForceOn"
	ResetTypePUSH_POWER_BUTTON ResetType = "PushPowerButton"
	ResetTypePOWER_CYCLE ResetType = "PowerCycle"
)