/*
 * Redfish API
 *
 * This contains the definition of a Redfish service.
 *
 * API version: 2018.3
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// The processor core metrics.
type CacheMetrics struct {
	// The number of cache line misses in millions.
	CacheMiss float32 `json:"CacheMiss,omitempty"`
	// The number of cache misses per instruction.
	CacheMissesPerInstruction float32 `json:"CacheMissesPerInstruction,omitempty"`
	// The cache line hit ratio.
	HitRatio float32 `json:"HitRatio,omitempty"`
	// The cache level.
	Level string `json:"Level,omitempty"`
	// The total cache level occupancy in bytes.
	OccupancyBytes int32 `json:"OccupancyBytes,omitempty"`
	// The total cache occupancy percentage.
	OccupancyPercent float32 `json:"OccupancyPercent,omitempty"`
}
