/*
 * Redfish API
 *
 * This contains the definition of a Redfish service.
 *
 * API version: 2018.3
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
type Health string

// List of Health
const (
	HealthOK Health = "OK"
	HealthWARNING Health = "Warning"
	HealthCRITICAL Health = "Critical"
)