/*
 * Redfish API
 *
 * This contains the definition of a Redfish service.
 *
 * API version: 2018.3
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
type ProcessorType string

// List of ProcessorType
const (
	ProcessorTypeCPU ProcessorType = "CPU"
	ProcessorTypeGPU ProcessorType = "GPU"
	ProcessorTypeFPGA ProcessorType = "FPGA"
	ProcessorTypeDSP ProcessorType = "DSP"
	ProcessorTypeACCELERATOR ProcessorType = "Accelerator"
	ProcessorTypeCORE ProcessorType = "Core"
	ProcessorTypeTHREAD ProcessorType = "Thread"
	ProcessorTypeOEM ProcessorType = "OEM"
)