/*
 * Redfish API
 *
 * This contains the definition of a Redfish service.
 *
 * API version: 2018.3
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// Calculable : The types of calculations which can be applied to the metric reading.  This property provides information to the client on the suitability of calculatiion using the metric reading.
type Calculable string

// List of Calculable
const (
	CalculableNON_CALCULATABLE Calculable = "NonCalculatable"
	CalculableSUMMABLE Calculable = "Summable"
	CalculableNON_SUMMABLE Calculable = "NonSummable"
)