/*
 * Redfish API
 *
 * This contains the definition of a Redfish service.
 *
 * API version: 2018.3
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// A Network Device Function represents a logical interface exposed by the network adapter.
type NetworkDeviceFunction struct {
	// The OData description of a payload.
	OdataContext string `json:"@odata.context,omitempty"`
	// The current ETag of the resource.
	OdataEtag string `json:"@odata.etag,omitempty"`
	// The unique identifier for a resource.
	OdataId string `json:"@odata.id"`
	// The type of a resource.
	OdataType string `json:"@odata.type"`
	Actions Actions2 `json:"Actions,omitempty"`
	// The array of physical port references that this network device function may be assigned to.
	AssignablePhysicalPorts []IdRef `json:"AssignablePhysicalPorts,omitempty"`
	// The number of items in a collection.
	AssignablePhysicalPortsodataCount int32 `json:"AssignablePhysicalPorts@odata.count,omitempty"`
	BootMode BootMode `json:"BootMode,omitempty"`
	// Provides a description of this resource and is used for commonality  in the schema definitions.
	Description string `json:"Description,omitempty"`
	// Whether the network device function is enabled.
	DeviceEnabled bool `json:"DeviceEnabled,omitempty"`
	Ethernet Ethernet `json:"Ethernet,omitempty"`
	FibreChannel FibreChannel `json:"FibreChannel,omitempty"`
	// Uniquely identifies the resource within the collection of like resources.
	Id string `json:"Id"`
	Links Links2 `json:"Links,omitempty"`
	// The number of virtual functions (VFs) that are available for this Network Device Function.
	MaxVirtualFunctions int32 `json:"MaxVirtualFunctions,omitempty"`
	// The name of the resource or array element.
	Name string `json:"Name"`
	// Capabilities of this network device function.
	NetDevFuncCapabilities []NetworkDeviceTechnology `json:"NetDevFuncCapabilities,omitempty"`
	NetDevFuncType NetworkDeviceTechnology `json:"NetDevFuncType,omitempty"`
	Oem Oem `json:"Oem,omitempty"`
	PhysicalPortAssignment IdRef `json:"PhysicalPortAssignment,omitempty"`
	Status Status `json:"Status,omitempty"`
	// Whether Single Root I/O Virtualization (SR-IOV) Virual Functions (VFs) are enabled for this Network Device Function.
	VirtualFunctionsEnabled bool `json:"VirtualFunctionsEnabled,omitempty"`
	ISCSIBoot IScsiBoot `json:"iSCSIBoot,omitempty"`
}
