/*
 * Redfish API
 *
 * This contains the definition of a Redfish service.
 *
 * API version: 2018.3
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
type StatusIndicator string

// List of StatusIndicator
const (
	StatusIndicatorOK StatusIndicator = "OK"
	StatusIndicatorFAIL StatusIndicator = "Fail"
	StatusIndicatorREBUILD StatusIndicator = "Rebuild"
	StatusIndicatorPREDICTIVE_FAILURE_ANALYSIS StatusIndicator = "PredictiveFailureAnalysis"
	StatusIndicatorHOTSPARE StatusIndicator = "Hotspare"
	StatusIndicatorIN_A_CRITICAL_ARRAY StatusIndicator = "InACriticalArray"
	StatusIndicatorIN_A_FAILED_ARRAY StatusIndicator = "InAFailedArray"
)