/*
 * Redfish API
 *
 * This contains the definition of a Redfish service.
 *
 * API version: 2018.3
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// This action is used to set the encryption key for the storage subsystem.
type SetEncryptionKeyRequestBody struct {
	// The encryption key to set on the storage subsytem.
	EncryptionKey string `json:"EncryptionKey"`
}
