/*
 * Redfish API
 *
 * This contains the definition of a Redfish service.
 *
 * API version: 2018.3
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// ReportUpdatesEnum : How to what to do with subsequent metric reports when a metric report already exists.
type ReportUpdatesEnum string

// List of ReportUpdatesEnum
const (
	ReportUpdatesEnumOVERWRITE ReportUpdatesEnum = "Overwrite"
	ReportUpdatesEnumAPPEND_WRAPS_WHEN_FULL ReportUpdatesEnum = "AppendWrapsWhenFull"
	ReportUpdatesEnumAPPEND_STOPS_WHEN_FULL ReportUpdatesEnum = "AppendStopsWhenFull"
	ReportUpdatesEnumNEW_REPORT ReportUpdatesEnum = "NewReport"
)