/*
 * Redfish API
 *
 * This contains the definition of a Redfish service.
 *
 * API version: 2018.3
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// A virtual function of a controller.
type VirtualFunction struct {
	// The maximum number of Virtual Functions (VFs) supported by this controller.
	DeviceMaxCount int32 `json:"DeviceMaxCount,omitempty"`
	// The minimum number of Virtual Functions (VFs) that can be allocated or moved between physical functions for this controller.
	MinAssignmentGroupSize int32 `json:"MinAssignmentGroupSize,omitempty"`
	// The maximum number of Virtual Functions (VFs) supported per network port for this controller.
	NetworkPortMaxCount int32 `json:"NetworkPortMaxCount,omitempty"`
}
