/*
 * Redfish API
 *
 * This contains the definition of a Redfish service.
 *
 * API version: 2018.3
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
type ChassisType string

// List of ChassisType
const (
	ChassisTypeRACK ChassisType = "Rack"
	ChassisTypeBLADE ChassisType = "Blade"
	ChassisTypeENCLOSURE ChassisType = "Enclosure"
	ChassisTypeSTAND_ALONE ChassisType = "StandAlone"
	ChassisTypeRACK_MOUNT ChassisType = "RackMount"
	ChassisTypeCARD ChassisType = "Card"
	ChassisTypeCARTRIDGE ChassisType = "Cartridge"
	ChassisTypeROW ChassisType = "Row"
	ChassisTypePOD ChassisType = "Pod"
	ChassisTypeEXPANSION ChassisType = "Expansion"
	ChassisTypeSIDECAR ChassisType = "Sidecar"
	ChassisTypeZONE ChassisType = "Zone"
	ChassisTypeSLED ChassisType = "Sled"
	ChassisTypeSHELF ChassisType = "Shelf"
	ChassisTypeDRAWER ChassisType = "Drawer"
	ChassisTypeMODULE ChassisType = "Module"
	ChassisTypeCOMPONENT ChassisType = "Component"
	ChassisTypeIP_BASED_DRIVE ChassisType = "IPBasedDrive"
	ChassisTypeRACK_GROUP ChassisType = "RackGroup"
	ChassisTypeSTORAGE_ENCLOSURE ChassisType = "StorageEnclosure"
	ChassisTypeOTHER ChassisType = "Other"
)