/*
 * Redfish API
 *
 * This contains the definition of a Redfish service.
 *
 * API version: 2018.3
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
type PowerLimitException string

// List of PowerLimitException
const (
	PowerLimitExceptionNO_ACTION PowerLimitException = "NoAction"
	PowerLimitExceptionHARD_POWER_OFF PowerLimitException = "HardPowerOff"
	PowerLimitExceptionLOG_EVENT_ONLY PowerLimitException = "LogEventOnly"
	PowerLimitExceptionOEM PowerLimitException = "Oem"
)