/*
 * Redfish API
 *
 * This contains the definition of a Redfish service.
 *
 * API version: 2018.3
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
type EncryptionAbility string

// List of EncryptionAbility
const (
	EncryptionAbilityNONE EncryptionAbility = "None"
	EncryptionAbilitySELF_ENCRYPTING_DRIVE EncryptionAbility = "SelfEncryptingDrive"
	EncryptionAbilityOTHER EncryptionAbility = "Other"
)