/*
 * Redfish API
 *
 * This contains the definition of a Redfish service.
 *
 * API version: 2018.3
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
type EnvironmentalClass string

// List of EnvironmentalClass
const (
	EnvironmentalClassA1 EnvironmentalClass = "A1"
	EnvironmentalClassA2 EnvironmentalClass = "A2"
	EnvironmentalClassA3 EnvironmentalClass = "A3"
	EnvironmentalClassA4 EnvironmentalClass = "A4"
)