/*
 * Redfish API
 *
 * This contains the definition of a Redfish service.
 *
 * API version: 2018.3
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// A minimum bandwidth allocation percentage for a Network Device Functions associated a port.
type NetDevFuncMinBwAlloc struct {
	// The minimum bandwidth allocation percentage allocated to the corresponding network device function instance.
	MinBWAllocPercent int32 `json:"MinBWAllocPercent,omitempty"`
	NetworkDeviceFunction IdRef `json:"NetworkDeviceFunction,omitempty"`
}
