/*
 * Redfish API
 *
 * This contains the definition of a Redfish service.
 *
 * API version: 2018.3
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// The Session resource describes a single connection (session) between a client and a Redfish service instance.
type Session struct {
	// The unique identifier for a resource.
	OdataId string `json:"@odata.id,omitempty"`
	// The OData description of a payload.
	OdataContext string `json:"@odata.context,omitempty"`
	// The type of a resource.
	OdataType string `json:"@odata.type,omitempty"`
	// Provides a description of this resource and is used for commonality  in the schema definitions.
	Description string `json:"Description,omitempty"`
	// Uniquely identifies the resource within the collection of like resources.
	Id string `json:"Id"`
	// The name of the resource or array element.
	Name string `json:"Name"`
	Oem Oem `json:"Oem,omitempty"`
	// This property is used in a POST to specify a password when creating a new session.  This property is null on a GET.
	Password string `json:"Password,omitempty"`
	// The UserName for the account for this session.
	UserName string `json:"UserName,omitempty"`
}
