/*
 * Redfish API
 *
 * This contains the definition of a Redfish service.
 *
 * API version: 2018.3
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// The set of thresholds defined for a sensor.
type Thresholds2 struct {
	LowerCritical Threshold2 `json:"LowerCritical,omitempty"`
	LowerWarning Threshold2 `json:"LowerWarning,omitempty"`
	UpperCritical Threshold2 `json:"UpperCritical,omitempty"`
	UpperWarning Threshold2 `json:"UpperWarning,omitempty"`
}
