/*
 * Redfish API
 *
 * This contains the definition of a Redfish service.
 *
 * API version: 2018.3
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// This is the schema definition for the PCIeFunction resource.  It represents the properties of a PCIeFunction attached to a System.
type PcIeFunction struct {
	// The OData description of a payload.
	OdataContext string `json:"@odata.context,omitempty"`
	// The current ETag of the resource.
	OdataEtag string `json:"@odata.etag,omitempty"`
	// The unique identifier for a resource.
	OdataId string `json:"@odata.id"`
	// The type of a resource.
	OdataType string `json:"@odata.type"`
	Actions Actions2 `json:"Actions,omitempty"`
	// The Class Code of this PCIe function.
	ClassCode string `json:"ClassCode,omitempty"`
	// Provides a description of this resource and is used for commonality  in the schema definitions.
	Description string `json:"Description,omitempty"`
	DeviceClass DeviceClass `json:"DeviceClass,omitempty"`
	// The Device ID of this PCIe function.
	DeviceId string `json:"DeviceId,omitempty"`
	// The the PCIe Function identifier.
	FunctionId int32 `json:"FunctionId,omitempty"`
	FunctionType FunctionType `json:"FunctionType,omitempty"`
	// Uniquely identifies the resource within the collection of like resources.
	Id string `json:"Id"`
	Links Links2 `json:"Links,omitempty"`
	// The name of the resource or array element.
	Name string `json:"Name"`
	Oem string `json:"Oem,omitempty"`
	// The Revision ID of this PCIe function.
	RevisionId string `json:"RevisionId,omitempty"`
	Status Status `json:"Status,omitempty"`
	// The Subsystem ID of this PCIe function.
	SubsystemId string `json:"SubsystemId,omitempty"`
	// The Subsystem Vendor ID of this PCIe function.
	SubsystemVendorId string `json:"SubsystemVendorId,omitempty"`
	// The Vendor ID of this PCIe function.
	VendorId string `json:"VendorId,omitempty"`
}
