/*
 * Redfish API
 *
 * This contains the definition of a Redfish service.
 *
 * API version: 2018.3
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type Fan struct {
	// The unique identifier for a resource.
	OdataId string `json:"@odata.id"`
	Actions FanActions `json:"Actions,omitempty"`
	Assembly IdRef `json:"Assembly,omitempty"`
	// Name of the fan.
	FanName string `json:"FanName,omitempty"`
	// Indicates if this device can be inserted or removed while the equipment is in operation.
	HotPluggable bool `json:"HotPluggable,omitempty"`
	IndicatorLED IndicatorLed2 `json:"IndicatorLED,omitempty"`
	Location Location `json:"Location,omitempty"`
	// Below normal range but not yet fatal.
	LowerThresholdCritical int32 `json:"LowerThresholdCritical,omitempty"`
	// Below normal range and is fatal.
	LowerThresholdFatal int32 `json:"LowerThresholdFatal,omitempty"`
	// Below normal range.
	LowerThresholdNonCritical int32 `json:"LowerThresholdNonCritical,omitempty"`
	// This is the manufacturer of this Fan.
	Manufacturer string `json:"Manufacturer,omitempty"`
	// Maximum value for Reading.
	MaxReadingRange int32 `json:"MaxReadingRange,omitempty"`
	// This is the identifier for the member within the collection.
	MemberId string `json:"MemberId"`
	// Minimum value for Reading.
	MinReadingRange int32 `json:"MinReadingRange,omitempty"`
	// The model number for this Fan.
	Model string `json:"Model,omitempty"`
	// Name of the fan.
	Name string `json:"Name,omitempty"`
	Oem Oem `json:"Oem,omitempty"`
	// The part number for this Fan.
	PartNumber string `json:"PartNumber,omitempty"`
	PhysicalContext IdRef `json:"PhysicalContext,omitempty"`
	// Current fan speed.
	Reading int32 `json:"Reading,omitempty"`
	ReadingUnits ReadingUnits `json:"ReadingUnits,omitempty"`
	// This structure is used to show redundancy for fans.  The Component ids will reference the members of the redundancy groups.
	Redundancy []IdRef `json:"Redundancy,omitempty"`
	// The number of items in a collection.
	RedundancyodataCount int32 `json:"Redundancy@odata.count,omitempty"`
	// The ID(s) of the resources serviced with this fan.
	RelatedItem []IdRef `json:"RelatedItem,omitempty"`
	// The number of items in a collection.
	RelatedItemodataCount int32 `json:"RelatedItem@odata.count,omitempty"`
	// A numerical identifier to represent the fan speed sensor.
	SensorNumber int32 `json:"SensorNumber,omitempty"`
	// The serial number for this Fan.
	SerialNumber string `json:"SerialNumber,omitempty"`
	// The spare part number for this Fan.
	SparePartNumber string `json:"SparePartNumber,omitempty"`
	Status Status `json:"Status,omitempty"`
	// Above normal range but not yet fatal.
	UpperThresholdCritical int32 `json:"UpperThresholdCritical,omitempty"`
	// Above normal range and is fatal.
	UpperThresholdFatal int32 `json:"UpperThresholdFatal,omitempty"`
	// Above normal range.
	UpperThresholdNonCritical int32 `json:"UpperThresholdNonCritical,omitempty"`
}
