/*
 * Redfish API
 *
 * This contains the definition of a Redfish service.
 *
 * API version: 2018.3
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// Contains information about protocol features supported by the service.
type ProtocolFeaturesSupported struct {
	// This indicates whether the 'excerpt' query parameter is supported.
	ExcerptQuery bool `json:"ExcerptQuery,omitempty"`
	ExpandQuery Expand `json:"ExpandQuery,omitempty"`
	// This indicates whether the $filter query parameter is supported.
	FilterQuery bool `json:"FilterQuery,omitempty"`
	// This indicates whether the 'only' query parameter is supported.
	OnlyMemberQuery bool `json:"OnlyMemberQuery,omitempty"`
	// This indicates whether the $select query parameter is supported.
	SelectQuery bool `json:"SelectQuery,omitempty"`
}
