/*
 * Redfish API
 *
 * This contains the definition of a Redfish service.
 *
 * API version: 2018.3
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// The C-state residency of the processor.
type CStateResidency struct {
	// The level of C-state, e.g. C0, C1, C2.
	Level string `json:"Level,omitempty"`
	// The percentage of time that the processor or core has spent in this particular level of C-state.
	ResidencyPercent float32 `json:"ResidencyPercent,omitempty"`
}
