/*
 * Redfish API
 *
 * This contains the definition of a Redfish service.
 *
 * API version: 2018.3
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// This is the schema definition for definition of a Memory and its configuration.
type Memory struct {
	// The OData description of a payload.
	OdataContext string `json:"@odata.context,omitempty"`
	// The current ETag of the resource.
	OdataEtag string `json:"@odata.etag,omitempty"`
	// The unique identifier for a resource.
	OdataId string `json:"@odata.id"`
	// The type of a resource.
	OdataType string `json:"@odata.type"`
	Actions Actions2 `json:"Actions,omitempty"`
	// The boundary which memory regions are allocated on, measured in mebibytes (MiB).
	AllocationAlignmentMiB int32 `json:"AllocationAlignmentMiB,omitempty"`
	// The size of the smallest unit of allocation for a memory region in mebibytes (MiB).
	AllocationIncrementMiB int32 `json:"AllocationIncrementMiB,omitempty"`
	// Speed bins supported by this Memory.
	AllowedSpeedsMHz []int32 `json:"AllowedSpeedsMHz,omitempty"`
	Assembly IdRef `json:"Assembly,omitempty"`
	BaseModuleType BaseModuleType `json:"BaseModuleType,omitempty"`
	// Bus Width in bits.
	BusWidthBits int32 `json:"BusWidthBits,omitempty"`
	// Total size of the cache portion memory in MiB.
	CacheSizeMiB int32 `json:"CacheSizeMiB,omitempty"`
	// Memory Capacity in mebibytes (MiB).
	CapacityMiB int32 `json:"CapacityMiB,omitempty"`
	// Indicates that the configuration of this memory has been locked.
	ConfigurationLocked bool `json:"ConfigurationLocked,omitempty"`
	// Data Width in bits.
	DataWidthBits int32 `json:"DataWidthBits,omitempty"`
	// Provides a description of this resource and is used for commonality  in the schema definitions.
	Description string `json:"Description,omitempty"`
	// Device ID.
	DeviceID string `json:"DeviceID,omitempty"`
	// Location of the Memory in the platform.
	DeviceLocator string `json:"DeviceLocator,omitempty"`
	ErrorCorrection ErrorCorrection `json:"ErrorCorrection,omitempty"`
	// Version of API supported by the firmware.
	FirmwareApiVersion string `json:"FirmwareApiVersion,omitempty"`
	// Revision of firmware on the Memory controller.
	FirmwareRevision string `json:"FirmwareRevision,omitempty"`
	// Function Classes by the Memory.
	FunctionClasses []string `json:"FunctionClasses,omitempty"`
	// Uniquely identifies the resource within the collection of like resources.
	Id string `json:"Id"`
	// Rank spare enabled status.
	IsRankSpareEnabled bool `json:"IsRankSpareEnabled,omitempty"`
	// Spare device enabled status.
	IsSpareDeviceEnabled bool `json:"IsSpareDeviceEnabled,omitempty"`
	Links Links2 `json:"Links,omitempty"`
	Location Location `json:"Location,omitempty"`
	// Total size of the logical memory in MiB.
	LogicalSizeMiB int32 `json:"LogicalSizeMiB,omitempty"`
	// The Memory manufacturer.
	Manufacturer string `json:"Manufacturer,omitempty"`
	// Maximum TDPs in milli Watts.
	MaxTDPMilliWatts []int32 `json:"MaxTDPMilliWatts,omitempty"`
	MemoryDeviceType MemoryDeviceType `json:"MemoryDeviceType,omitempty"`
	MemoryLocation MemoryLocation `json:"MemoryLocation,omitempty"`
	// Media of this Memory.
	MemoryMedia []MemoryMedia `json:"MemoryMedia,omitempty"`
	// The manufacturer ID of the memory subsystem controller of this memory module.
	MemorySubsystemControllerManufacturerID string `json:"MemorySubsystemControllerManufacturerID,omitempty"`
	// The product ID of the memory subsystem controller of this memory module.
	MemorySubsystemControllerProductID string `json:"MemorySubsystemControllerProductID,omitempty"`
	MemoryType MemoryType `json:"MemoryType,omitempty"`
	Metrics IdRef `json:"Metrics,omitempty"`
	// The manufacturer ID of this memory module.
	ModuleManufacturerID string `json:"ModuleManufacturerID,omitempty"`
	// The product ID of this memory module.
	ModuleProductID string `json:"ModuleProductID,omitempty"`
	// The name of the resource or array element.
	Name string `json:"Name"`
	// Total size of the non-volatile portion memory in MiB.
	NonVolatileSizeMiB int32 `json:"NonVolatileSizeMiB,omitempty"`
	Oem Oem `json:"Oem,omitempty"`
	// Memory modes supported by the Memory.
	OperatingMemoryModes []OperatingMemoryModes `json:"OperatingMemoryModes,omitempty"`
	// Operating speed of Memory in MHz or MT/s as appropriate.
	OperatingSpeedMhz int32 `json:"OperatingSpeedMhz,omitempty"`
	// The product part number of this device.
	PartNumber string `json:"PartNumber,omitempty"`
	// Total number of persistent regions this Memory can support.
	PersistentRegionNumberLimit int32 `json:"PersistentRegionNumberLimit,omitempty"`
	// Total size of persistent regions in mebibytes (MiB).
	PersistentRegionSizeLimitMiB int32 `json:"PersistentRegionSizeLimitMiB,omitempty"`
	// Maximum size of a single persistent region in mebibytes (MiB).
	PersistentRegionSizeMaxMiB int32 `json:"PersistentRegionSizeMaxMiB,omitempty"`
	PowerManagementPolicy PowerManagementPolicy `json:"PowerManagementPolicy,omitempty"`
	// Number of ranks available in the Memory.
	RankCount int32 `json:"RankCount,omitempty"`
	// Memory regions information within the Memory.
	Regions []RegionSet `json:"Regions,omitempty"`
	SecurityCapabilities SecurityCapabilities `json:"SecurityCapabilities,omitempty"`
	SecurityState SecurityStates `json:"SecurityState,omitempty"`
	// The product serial number of this device.
	SerialNumber string `json:"SerialNumber,omitempty"`
	// Number of unused spare devices available in the Memory.
	SpareDeviceCount int32 `json:"SpareDeviceCount,omitempty"`
	Status Status `json:"Status,omitempty"`
	// Subsystem Device ID.
	SubsystemDeviceID string `json:"SubsystemDeviceID,omitempty"`
	// SubSystem Vendor ID.
	SubsystemVendorID string `json:"SubsystemVendorID,omitempty"`
	// Vendor ID.
	VendorID string `json:"VendorID,omitempty"`
	// Total number of volatile regions this Memory can support.
	VolatileRegionNumberLimit int32 `json:"VolatileRegionNumberLimit,omitempty"`
	// Total size of volatile regions in mebibytes (MiB).
	VolatileRegionSizeLimitMiB int32 `json:"VolatileRegionSizeLimitMiB,omitempty"`
	// Maximum size of a single volatile region in mebibytes (MiB).
	VolatileRegionSizeMaxMiB int32 `json:"VolatileRegionSizeMaxMiB,omitempty"`
	// Total size of the volitile portion memory in MiB.
	VolatileSizeMiB int32 `json:"VolatileSizeMiB,omitempty"`
}
