/*
 * Redfish API
 *
 * This contains the definition of a Redfish service.
 *
 * API version: 2018.3
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// This is the definition for an Ethernet Interface object.
type EthernetInterface2 struct {
	// This is the number of lanes supported by this interface.
	MaxLanes int32 `json:"MaxLanes,omitempty"`
	// The maximum speed supported by this interface.
	MaxSpeedMbps int32 `json:"MaxSpeedMbps,omitempty"`
	Oem string `json:"Oem,omitempty"`
}
