/*
 * Redfish API
 *
 * This contains the definition of a Redfish service.
 *
 * API version: 2018.3
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
type VoltageType string

// List of VoltageType
const (
	VoltageTypeAC VoltageType = "AC"
	VoltageTypeDC VoltageType = "DC"
)