/*
 * Redfish API
 *
 * This contains the definition of a Redfish service.
 *
 * API version: 2018.3
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// DHCPv6 configuration for this interface.
type DhcPv6Configuration struct {
	OperatingMode DhcPv6OperatingMode `json:"OperatingMode,omitempty"`
	// When enabled, DNS server addresses supplied through DHCPv6 stateless mode will be used.
	UseDNSServers bool `json:"UseDNSServers,omitempty"`
	// When enabled, the domain name supplied through DHCPv6 stateless mode will be used.
	UseDomainName bool `json:"UseDomainName,omitempty"`
	// When enabled, NTP server addresses supplied through DHCPv6 stateless mode will be used.
	UseNTPServers bool `json:"UseNTPServers,omitempty"`
	// Determines whether to use DHCPv6 rapid commit mode for stateful mode address assignments. Do not enable in networks where more than one DHCPv6 server is configured to provide address assignments.
	UseRapidCommit bool `json:"UseRapidCommit,omitempty"`
}
