/*
 * Redfish API
 *
 * This contains the definition of a Redfish service.
 *
 * API version: 2018.3
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
type InstructionSet string

// List of InstructionSet
const (
	InstructionSetX86 InstructionSet = "x86"
	InstructionSetX86_64 InstructionSet = "x86-64"
	InstructionSetIA_64 InstructionSet = "IA-64"
	InstructionSetARM_A32 InstructionSet = "ARM-A32"
	InstructionSetARM_A64 InstructionSet = "ARM-A64"
	InstructionSetMIPS32 InstructionSet = "MIPS32"
	InstructionSetMIPS64 InstructionSet = "MIPS64"
	InstructionSetPOWER_ISA InstructionSet = "PowerISA"
	InstructionSetOEM InstructionSet = "OEM"
)