/*
 * Redfish API
 *
 * This contains the definition of a Redfish service.
 *
 * API version: 2018.3
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
type NetworkDeviceTechnology string

// List of NetworkDeviceTechnology
const (
	NetworkDeviceTechnologyDISABLED NetworkDeviceTechnology = "Disabled"
	NetworkDeviceTechnologyETHERNET NetworkDeviceTechnology = "Ethernet"
	NetworkDeviceTechnologyFIBRE_CHANNEL NetworkDeviceTechnology = "FibreChannel"
	NetworkDeviceTechnologyI_SCSI NetworkDeviceTechnology = "iSCSI"
	NetworkDeviceTechnologyFIBRE_CHANNEL_OVER_ETHERNET NetworkDeviceTechnology = "FibreChannelOverEthernet"
)