/*
 * Redfish API
 *
 * This contains the definition of a Redfish service.
 *
 * API version: 2018.3
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type IPv4Address2 struct {
	// This is the IPv4 Address.
	Address string `json:"Address,omitempty"`
	AddressOrigin IPv4AddressOrigin `json:"AddressOrigin,omitempty"`
	// This is the IPv4 gateway for this address.
	Gateway string `json:"Gateway,omitempty"`
	Oem Oem `json:"Oem,omitempty"`
	SubnetMask string `json:"SubnetMask,omitempty"`
}
