/*
 * Redfish API
 *
 * This contains the definition of a Redfish service.
 *
 * API version: 2018.3
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
type SerialConnectTypesSupported string

// List of SerialConnectTypesSupported
const (
	SerialConnectTypesSupportedSSH SerialConnectTypesSupported = "SSH"
	SerialConnectTypesSupportedTELNET SerialConnectTypesSupported = "Telnet"
	SerialConnectTypesSupportedIPMI SerialConnectTypesSupported = "IPMI"
	SerialConnectTypesSupportedOEM SerialConnectTypesSupported = "Oem"
)