/*
 * Redfish API
 *
 * This contains the definition of a Redfish service.
 *
 * API version: 2018.3
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
type PowerSupplyType string

// List of PowerSupplyType
const (
	PowerSupplyTypeUNKNOWN PowerSupplyType = "Unknown"
	PowerSupplyTypeAC PowerSupplyType = "AC"
	PowerSupplyTypeDC PowerSupplyType = "DC"
	PowerSupplyTypeA_COR_DC PowerSupplyType = "ACorDC"
)