/*
 * Redfish API
 *
 * This contains the definition of a Redfish service.
 *
 * API version: 2018.3
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// This type describes the health information of the memory.
type HealthData struct {
	AlarmTrips AlarmTrips `json:"AlarmTrips,omitempty"`
	// Data loss detection status.
	DataLossDetected bool `json:"DataLossDetected,omitempty"`
	// Status of last shutdown.
	LastShutdownSuccess bool `json:"LastShutdownSuccess,omitempty"`
	// Performance degraded mode status.
	PerformanceDegraded bool `json:"PerformanceDegraded,omitempty"`
	// The percentage of reads and writes that are predicted to still be available for the media.
	PredictedMediaLifeLeftPercent float32 `json:"PredictedMediaLifeLeftPercent,omitempty"`
	// Remaining spare blocks in percentage.
	RemainingSpareBlockPercentage float32 `json:"RemainingSpareBlockPercentage,omitempty"`
}
