/*
 * Redfish API
 *
 * This contains the definition of a Redfish service.
 *
 * API version: 2018.3
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// Power management policy information.
type PowerManagementPolicy struct {
	// Average power budget in milli watts.
	AveragePowerBudgetMilliWatts int32 `json:"AveragePowerBudgetMilliWatts,omitempty"`
	// Maximum TDP in milli watts.
	MaxTDPMilliWatts int32 `json:"MaxTDPMilliWatts,omitempty"`
	// Peak power budget in milli watts.
	PeakPowerBudgetMilliWatts int32 `json:"PeakPowerBudgetMilliWatts,omitempty"`
	// Power management policy enabled status.
	PolicyEnabled bool `json:"PolicyEnabled,omitempty"`
}
