/*
 * Redfish API
 *
 * This contains the definition of a Redfish service.
 *
 * API version: 2018.3
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// The capabilities of a controller.
type ControllerCapabilities struct {
	DataCenterBridging DataCenterBridging `json:"DataCenterBridging,omitempty"`
	NPAR NicPartitioning `json:"NPAR,omitempty"`
	NPIV Npiv `json:"NPIV,omitempty"`
	// The maximum number of physical functions available on this controller.
	NetworkDeviceFunctionCount int32 `json:"NetworkDeviceFunctionCount,omitempty"`
	// The number of physical ports on this controller.
	NetworkPortCount int32 `json:"NetworkPortCount,omitempty"`
	VirtualizationOffload VirtualizationOffload `json:"VirtualizationOffload,omitempty"`
}
