/*
 * Redfish API
 *
 * This contains the definition of a Redfish service.
 *
 * API version: 2018.3
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// CalculationAlgorithmEnum2 : Specifies the function to apply to the list of metric properties.
type CalculationAlgorithmEnum2 string

// List of CalculationAlgorithmEnum_2
const (
	CalculationAlgorithmEnum2AVERAGE CalculationAlgorithmEnum2 = "Average"
	CalculationAlgorithmEnum2MAXIMUM CalculationAlgorithmEnum2 = "Maximum"
	CalculationAlgorithmEnum2MINIMUM CalculationAlgorithmEnum2 = "Minimum"
	CalculationAlgorithmEnum2SUMMATION CalculationAlgorithmEnum2 = "Summation"
)