/*
 * Redfish API
 *
 * This contains the definition of a Redfish service.
 *
 * API version: 2018.3
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
type MemoryMirroring string

// List of MemoryMirroring
const (
	MemoryMirroringSYSTEM MemoryMirroring = "System"
	MemoryMirroringDIMM MemoryMirroring = "DIMM"
	MemoryMirroringHYBRID MemoryMirroring = "Hybrid"
	MemoryMirroringNONE MemoryMirroring = "None"
)