/*
 * Redfish API
 *
 * This contains the definition of a Redfish service.
 *
 * API version: 2018.3
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
type DhcPv6OperatingMode string

// List of DHCPv6OperatingMode
const (
	DhcPv6OperatingModeSTATEFUL DhcPv6OperatingMode = "Stateful"
	DhcPv6OperatingModeSTATELESS DhcPv6OperatingMode = "Stateless"
	DhcPv6OperatingModeDISABLED DhcPv6OperatingMode = "Disabled"
)