/*
 * Redfish API
 *
 * This contains the definition of a Redfish service.
 *
 * API version: 2018.3
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
type DeviceType string

// List of DeviceType
const (
	DeviceTypeSINGLE_FUNCTION DeviceType = "SingleFunction"
	DeviceTypeMULTI_FUNCTION DeviceType = "MultiFunction"
	DeviceTypeSIMULATED DeviceType = "Simulated"
)