/*
 * Redfish API
 *
 * This contains the definition of a Redfish service.
 *
 * API version: 2018.3
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
type ElectricalContext string

// List of ElectricalContext
const (
	ElectricalContextLINE1 ElectricalContext = "Line1"
	ElectricalContextLINE2 ElectricalContext = "Line2"
	ElectricalContextLINE3 ElectricalContext = "Line3"
	ElectricalContextNEUTRAL ElectricalContext = "Neutral"
	ElectricalContextLINE_TO_LINE ElectricalContext = "LineToLine"
	ElectricalContextLINE1_TO_LINE2 ElectricalContext = "Line1ToLine2"
	ElectricalContextLINE2_TO_LINE3 ElectricalContext = "Line2ToLine3"
	ElectricalContextLINE3_TO_LINE1 ElectricalContext = "Line3ToLine1"
	ElectricalContextLINE_TO_NEUTRAL ElectricalContext = "LineToNeutral"
	ElectricalContextLINE1_TO_NEUTRAL ElectricalContext = "Line1ToNeutral"
	ElectricalContextLINE2_TO_NEUTRAL ElectricalContext = "Line2ToNeutral"
	ElectricalContextLINE3_TO_NEUTRAL ElectricalContext = "Line3ToNeutral"
	ElectricalContextLINE1_TO_NEUTRAL_AND_L1_L2 ElectricalContext = "Line1ToNeutralAndL1L2"
	ElectricalContextLINE2_TO_NEUTRAL_AND_L1_L2 ElectricalContext = "Line2ToNeutralAndL1L2"
	ElectricalContextLINE2_TO_NEUTRAL_AND_L2_L3 ElectricalContext = "Line2ToNeutralAndL2L3"
	ElectricalContextLINE3_TO_NEUTRAL_AND_L3_L1 ElectricalContext = "Line3ToNeutralAndL3L1"
	ElectricalContextTOTAL ElectricalContext = "Total"
)