/*
 * Redfish API
 *
 * This contains the definition of a Redfish service.
 *
 * API version: 2018.3
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// The EthernetInterface schema represents a single, logical ethernet interface or network interface controller (NIC).
type EthernetInterface struct {
	// The OData description of a payload.
	OdataContext string `json:"@odata.context,omitempty"`
	// The current ETag of the resource.
	OdataEtag string `json:"@odata.etag,omitempty"`
	// The unique identifier for a resource.
	OdataId string `json:"@odata.id"`
	// The type of a resource.
	OdataType string `json:"@odata.type"`
	Actions Actions2 `json:"Actions,omitempty"`
	// This indicates if the speed and duplex are automatically negotiated and configured on this interface.
	AutoNeg bool `json:"AutoNeg,omitempty"`
	DHCPv4 DhcPv4Configuration `json:"DHCPv4,omitempty"`
	DHCPv6 DhcPv6Configuration `json:"DHCPv6,omitempty"`
	// Provides a description of this resource and is used for commonality  in the schema definitions.
	Description string `json:"Description,omitempty"`
	// This is the complete, fully qualified domain name obtained by DNS for this interface.
	FQDN string `json:"FQDN,omitempty"`
	// This indicates if the interface is in Full Duplex mode or not.
	FullDuplex bool `json:"FullDuplex,omitempty"`
	// The DNS Host Name, without any domain information.
	HostName string `json:"HostName,omitempty"`
	// The IPv4 addresses currently assigned to this interface.
	IPv4Addresses []IPv4Address `json:"IPv4Addresses,omitempty"`
	// The IPv4 static addresses assigned to this interface.
	IPv4StaticAddresses []IPv4Address `json:"IPv4StaticAddresses,omitempty"`
	// An array representing the RFC 6724 Address Selection Policy Table.
	IPv6AddressPolicyTable []IPv6AddressPolicyEntry `json:"IPv6AddressPolicyTable,omitempty"`
	// Enumerates in an array all of the currently assigned IPv6 addresses on this interface.
	IPv6Addresses []IPv6Address `json:"IPv6Addresses,omitempty"`
	// This is the IPv6 default gateway address that is currently in use on this interface.
	IPv6DefaultGateway string `json:"IPv6DefaultGateway,omitempty"`
	// Represents in an array all of the IPv6 static addresses to be assigned on this interface.
	IPv6StaticAddresses []IPv6StaticAddress `json:"IPv6StaticAddresses,omitempty"`
	// The IPv6 static default gateways for this interface.
	IPv6StaticDefaultGateways []IPv6GatewayStaticAddress `json:"IPv6StaticDefaultGateways,omitempty"`
	// Uniquely identifies the resource within the collection of like resources.
	Id string `json:"Id"`
	// This indicates whether this interface is enabled.
	InterfaceEnabled bool `json:"InterfaceEnabled,omitempty"`
	LinkStatus LinkStatus2 `json:"LinkStatus,omitempty"`
	Links Links2 `json:"Links,omitempty"`
	MACAddress string `json:"MACAddress,omitempty"`
	// This is the currently configured Maximum Transmission Unit (MTU) in bytes on this interface.
	MTUSize int32 `json:"MTUSize,omitempty"`
	// This indicates the maximum number of Static IPv6 addresses that can be configured on this interface.
	MaxIPv6StaticAddresses int32 `json:"MaxIPv6StaticAddresses,omitempty"`
	// The name of the resource or array element.
	Name string `json:"Name"`
	// This represents DNS name servers that are currently in use on this interface.
	NameServers []string `json:"NameServers,omitempty"`
	Oem Oem `json:"Oem,omitempty"`
	PermanentMACAddress string `json:"PermanentMACAddress,omitempty"`
	// This is the current speed in Mbps of this interface.
	SpeedMbps int32 `json:"SpeedMbps,omitempty"`
	StatelessAddressAutoConfig StatelessAddressAutoConfiguration `json:"StatelessAddressAutoConfig,omitempty"`
	// A statically defined set of DNS server IP addresses (both IPv4 and IPv6).
	StaticNameServers []string `json:"StaticNameServers,omitempty"`
	Status Status `json:"Status,omitempty"`
	// The UEFI device path for this interface.
	UefiDevicePath string `json:"UefiDevicePath,omitempty"`
	VLAN Vlan `json:"VLAN,omitempty"`
	VLANs IdRef `json:"VLANs,omitempty"`
}
