/*
 * Redfish API
 *
 * This contains the definition of a Redfish service.
 *
 * API version: 2018.3
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// This action is to clear the settings back to factory defaults.
type ResetSettingsToDefaultRequestBody struct {
}
