/*
 * Redfish API
 *
 * This contains the definition of a Redfish service.
 *
 * API version: 2018.3
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// Settings for a network protocol associated with a manager.
type SsdProtocol struct {
	NotifyIPv6Scope NotifyIPv6Scope `json:"NotifyIPv6Scope,omitempty"`
	// Indicates how often the Multicast is done from this service for SSDP.
	NotifyMulticastIntervalSeconds int32 `json:"NotifyMulticastIntervalSeconds,omitempty"`
	// Indicates the time to live hop count for SSDPs Notify messages.
	NotifyTTL int32 `json:"NotifyTTL,omitempty"`
	// Indicates the protocol port.
	Port int32 `json:"Port,omitempty"`
	// Indicates if the protocol is enabled or disabled.
	ProtocolEnabled bool `json:"ProtocolEnabled,omitempty"`
}
