/*
 * Redfish API
 *
 * This contains the definition of a Redfish service.
 *
 * API version: 2018.3
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// A reference to a resource.
type IdRef struct {
	// The unique identifier for a resource.
	OdataId string `json:"@odata.id,omitempty"`
}
