/*
 * Redfish API
 *
 * This contains the definition of a Redfish service.
 *
 * API version: 2018.3
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// This type describes Fibre Channel capabilities, status, and configuration of a network device function.
type FibreChannel struct {
	// Whether the FCoE Initialization Protocol (FIP) is used for populating the FCoE VLAN Id.
	AllowFIPVLANDiscovery bool `json:"AllowFIPVLANDiscovery,omitempty"`
	// An array of Fibre Channel boot targets configured for this network device function.
	BootTargets []BootTargets `json:"BootTargets,omitempty"`
	// The active FCoE VLAN ID.
	FCoEActiveVLANId int32 `json:"FCoEActiveVLANId,omitempty"`
	// The locally configured FCoE VLAN ID.
	FCoELocalVLANId int32 `json:"FCoELocalVLANId,omitempty"`
	// The Fibre Channel Id assigned by the switch for this interface.
	FibreChannelId string `json:"FibreChannelId,omitempty"`
	// This is the permanent WWNN address assigned to this network device function (physical function).
	PermanentWWNN string `json:"PermanentWWNN,omitempty"`
	// This is the permanent WWPN address assigned to this network device function (physical function).
	PermanentWWPN string `json:"PermanentWWPN,omitempty"`
	// This is the currently configured WWNN address of the network device function (physical function).
	WWNN string `json:"WWNN,omitempty"`
	WWNSource WwnSource `json:"WWNSource,omitempty"`
	// This is the currently configured WWPN address of the network device function (physical function).
	WWPN string `json:"WWPN,omitempty"`
}
