/*
 * Redfish API
 *
 * This contains the definition of a Redfish service.
 *
 * API version: 2018.3
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// WatchdogTimeoutActions : The enumerations of WatchdogTimeoutActions specify the choice of action to take when the Host Watchdog Timer reaches its timeout value.
type WatchdogTimeoutActions string

// List of WatchdogTimeoutActions
const (
	WatchdogTimeoutActionsNONE WatchdogTimeoutActions = "None"
	WatchdogTimeoutActionsRESET_SYSTEM WatchdogTimeoutActions = "ResetSystem"
	WatchdogTimeoutActionsPOWER_CYCLE WatchdogTimeoutActions = "PowerCycle"
	WatchdogTimeoutActionsPOWER_DOWN WatchdogTimeoutActions = "PowerDown"
	WatchdogTimeoutActionsOEM WatchdogTimeoutActions = "OEM"
)