/*
 * Redfish API
 *
 * This contains the definition of a Redfish service.
 *
 * API version: 2018.3
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
type AddressState string

// List of AddressState
const (
	AddressStatePREFERRED AddressState = "Preferred"
	AddressStateDEPRECATED AddressState = "Deprecated"
	AddressStateTENTATIVE AddressState = "Tentative"
	AddressStateFAILED AddressState = "Failed"
)