/*
 * Redfish API
 *
 * This contains the definition of a Redfish service.
 *
 * API version: 2018.3
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
type State string

// List of State
const (
	StateENABLED State = "Enabled"
	StateDISABLED State = "Disabled"
	StateSTANDBY_OFFLINE State = "StandbyOffline"
	StateSTANDBY_SPARE State = "StandbySpare"
	StateIN_TEST State = "InTest"
	StateSTARTING State = "Starting"
	StateABSENT State = "Absent"
	StateUNAVAILABLE_OFFLINE State = "UnavailableOffline"
	StateDEFERRING State = "Deferring"
	StateQUIESCED State = "Quiesced"
	StateUPDATING State = "Updating"
)