/*
 * Redfish API
 *
 * This contains the definition of a Redfish service.
 *
 * API version: 2018.3
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
type IPv4AddressOrigin string

// List of IPv4AddressOrigin
const (
	IPv4AddressOriginSTATIC IPv4AddressOrigin = "Static"
	IPv4AddressOriginDHCP IPv4AddressOrigin = "DHCP"
	IPv4AddressOriginBOOTP IPv4AddressOrigin = "BOOTP"
	IPv4AddressOriginI_PV4_LINK_LOCAL IPv4AddressOrigin = "IPv4LinkLocal"
)