/*
 * Redfish API
 *
 * This contains the definition of a Redfish service.
 *
 * API version: 2018.3
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
type ApplyTime string

// List of ApplyTime
const (
	ApplyTimeIMMEDIATE ApplyTime = "Immediate"
	ApplyTimeON_RESET ApplyTime = "OnReset"
	ApplyTimeAT_MAINTENANCE_WINDOW_START ApplyTime = "AtMaintenanceWindowStart"
	ApplyTimeIN_MAINTENANCE_WINDOW_ON_RESET ApplyTime = "InMaintenanceWindowOnReset"
)