/*
 * Redfish API
 *
 * This contains the definition of a Redfish service.
 *
 * API version: 2018.3
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// Data Center Bridging (DCB) for capabilities of a controller.
type DataCenterBridging struct {
	// Whether this controller is capable of Data Center Bridging (DCB).
	Capable bool `json:"Capable,omitempty"`
}
