/*
 * Redfish API
 *
 * This contains the definition of a Redfish service.
 *
 * API version: 2018.3
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// Contains settings for searching a generic LDAP service.
type LdapSearchSettings struct {
	// The base distinguished names to use when searching the LDAP service.
	BaseDistinguishedNames []string `json:"BaseDistinguishedNames,omitempty"`
	// The attribute name that contains the name of the Group.
	GroupNameAttribute string `json:"GroupNameAttribute,omitempty"`
	// The attribute name that contains the Groups for a user.
	GroupsAttribute string `json:"GroupsAttribute,omitempty"`
	// The attribute name that contains the Username.
	UsernameAttribute string `json:"UsernameAttribute,omitempty"`
}
