/*
 * Redfish API
 *
 * This contains the definition of a Redfish service.
 *
 * API version: 2018.3
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
type TransferProtocolType2 string

// List of TransferProtocolType_2
const (
	TransferProtocolType2CIFS TransferProtocolType2 = "CIFS"
	TransferProtocolType2FTP TransferProtocolType2 = "FTP"
	TransferProtocolType2SFTP TransferProtocolType2 = "SFTP"
	TransferProtocolType2HTTP TransferProtocolType2 = "HTTP"
	TransferProtocolType2HTTPS TransferProtocolType2 = "HTTPS"
	TransferProtocolType2NSF TransferProtocolType2 = "NSF"
	TransferProtocolType2SCP TransferProtocolType2 = "SCP"
	TransferProtocolType2TFTP TransferProtocolType2 = "TFTP"
	TransferProtocolType2OEM TransferProtocolType2 = "OEM"
	TransferProtocolType2NFS TransferProtocolType2 = "NFS"
)