/*
 * Redfish API
 *
 * This contains the definition of a Redfish service.
 *
 * API version: 2018.3
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// This object describes the supported capabilities of this Job Service implementation.
type JobServiceCapabilities struct {
	// Maximum number of Jobs supported.
	MaxJobs int32 `json:"MaxJobs,omitempty"`
	// Maximum number of Job Steps supported.
	MaxSteps int32 `json:"MaxSteps,omitempty"`
	// Indicates whether scheduling of Jobs is supported.
	Scheduling bool `json:"Scheduling,omitempty"`
}
