/*
 * Redfish API
 *
 * This contains the definition of a Redfish service.
 *
 * API version: 2018.3
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// This type describes an interface to the FPGA.
type FpgaInterface struct {
	Ethernet EthernetInterface2 `json:"Ethernet,omitempty"`
	InterfaceType FpgaInterfaceType `json:"InterfaceType,omitempty"`
	PCIe PcIeInterface `json:"PCIe,omitempty"`
}
