/*
 * Redfish API
 *
 * This contains the definition of a Redfish service.
 *
 * API version: 2018.3
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// This type describes a Message returned by the Redfish service.
type Message struct {
	// This is the human readable message, if provided.
	Message string `json:"Message,omitempty"`
	// This array of message arguments are substituted for the arguments in the message when looked up in the message registry.
	MessageArgs []string `json:"MessageArgs,omitempty"`
	// This is the key for this message which can be used to look up the message in a message registry.
	MessageId string `json:"MessageId"`
	Oem string `json:"Oem,omitempty"`
	// This is an array of properties described by the message.
	RelatedProperties []string `json:"RelatedProperties,omitempty"`
	// Used to provide suggestions on how to resolve the situation that caused the error.
	Resolution string `json:"Resolution,omitempty"`
	// This is the severity of the errors.
	Severity string `json:"Severity,omitempty"`
}
