/*
 * Redfish API
 *
 * This contains the definition of a Redfish service.
 *
 * API version: 2018.3
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
type HotspareReplacementModeType string

// List of HotspareReplacementModeType
const (
	HotspareReplacementModeTypeREVERTIBLE HotspareReplacementModeType = "Revertible"
	HotspareReplacementModeTypeNON_REVERTIBLE HotspareReplacementModeType = "NonRevertible"
)