/*
 * Redfish API
 *
 * This contains the definition of a Redfish service.
 *
 * API version: 2018.3
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// MetricReportDefinitionType : Indicates when the metric report is generated.
type MetricReportDefinitionType string

// List of MetricReportDefinitionType
const (
	MetricReportDefinitionTypePERIODIC MetricReportDefinitionType = "Periodic"
	MetricReportDefinitionTypeON_CHANGE MetricReportDefinitionType = "OnChange"
	MetricReportDefinitionTypeON_REQUEST MetricReportDefinitionType = "OnRequest"
)