/*
 * Redfish API
 *
 * This contains the definition of a Redfish service.
 *
 * API version: 2018.3
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// The characteristics of the discrete trigger.
type DiscreteTrigger struct {
	// This time the trigger occurance persists before a trigger event has occurred.
	DwellTime string `json:"DwellTime,omitempty"`
	// The name of trigger.
	Name string `json:"Name,omitempty"`
	Severity Health `json:"Severity,omitempty"`
	// The value of the discrete metric that constitutes a trigger occurance.
	Value string `json:"Value,omitempty"`
}
