/*
 * Redfish API
 *
 * This contains the definition of a Redfish service.
 *
 * API version: 2018.3
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// The CompositionService schema defines a Composition Service which represents the properties for the service and links to the resources available for composition.
type CompositionService struct {
	// The OData description of a payload.
	OdataContext string `json:"@odata.context,omitempty"`
	// The current ETag of the resource.
	OdataEtag string `json:"@odata.etag,omitempty"`
	// The unique identifier for a resource.
	OdataId string `json:"@odata.id"`
	// The type of a resource.
	OdataType string `json:"@odata.type"`
	Actions Actions2 `json:"Actions,omitempty"`
	// This indicates whether this service is allowed to overprovision a composition relative to the composition request.
	AllowOverprovisioning bool `json:"AllowOverprovisioning,omitempty"`
	// This indicates whether a client is allowed to request that given composition request is fulfilled by a specified Resource Zone.
	AllowZoneAffinity bool `json:"AllowZoneAffinity,omitempty"`
	// Provides a description of this resource and is used for commonality  in the schema definitions.
	Description string `json:"Description,omitempty"`
	// Uniquely identifies the resource within the collection of like resources.
	Id string `json:"Id"`
	// The name of the resource or array element.
	Name string `json:"Name"`
	Oem string `json:"Oem,omitempty"`
	ResourceBlocks IdRef `json:"ResourceBlocks,omitempty"`
	ResourceZones IdRef `json:"ResourceZones,omitempty"`
	// This indicates whether this service is enabled.
	ServiceEnabled bool `json:"ServiceEnabled,omitempty"`
	Status Status `json:"Status,omitempty"`
}
