/*
 * Redfish API
 *
 * This contains the definition of a Redfish service.
 *
 * API version: 2018.3
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
type ThresholdActivation2 string

// List of ThresholdActivation_2
const (
	ThresholdActivation2INCREASING ThresholdActivation2 = "Increasing"
	ThresholdActivation2DECREASING ThresholdActivation2 = "Decreasing"
	ThresholdActivation2EITHER ThresholdActivation2 = "Either"
)