/*
 * Redfish API
 *
 * This contains the definition of a Redfish service.
 *
 * API version: 2018.3
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// TriggerActionEnum : Specifies the actions to perform when a trigger occurs.
type TriggerActionEnum string

// List of TriggerActionEnum
const (
	TriggerActionEnumLOG_TO_LOG_SERVICE TriggerActionEnum = "LogToLogService"
	TriggerActionEnumREDFISH_EVENT TriggerActionEnum = "RedfishEvent"
)