/*
 * Redfish API
 *
 * This contains the definition of a Redfish service.
 *
 * API version: 2018.3
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
import (
	"time"
)

// This resource defines the record format for a log.  It is designed to be used for SEL logs (from IPMI) as well as Event Logs and OEM-specific log formats.  The EntryType field indicates the type of log and the resource includes several additional properties dependent on the EntryType.
type LogEntry struct {
	// The OData description of a payload.
	OdataContext string `json:"@odata.context,omitempty"`
	// The current ETag of the resource.
	OdataEtag string `json:"@odata.etag,omitempty"`
	// The unique identifier for a resource.
	OdataId string `json:"@odata.id"`
	// The type of a resource.
	OdataType string `json:"@odata.type"`
	Actions Actions2 `json:"Actions,omitempty"`
	// The time the log entry was created.
	Created time.Time `json:"Created,omitempty"`
	// Provides a description of this resource and is used for commonality  in the schema definitions.
	Description string `json:"Description,omitempty"`
	EntryCode LogEntryCode `json:"EntryCode,omitempty"`
	EntryType LogEntryType `json:"EntryType"`
	// This value is the identifier used to correlate events that came from the same cause.
	EventGroupId int32 `json:"EventGroupId,omitempty"`
	// This is a unique instance identifier of an event.
	EventId string `json:"EventId,omitempty"`
	// This is time the event occurred.
	EventTimestamp time.Time `json:"EventTimestamp,omitempty"`
	EventType EventType `json:"EventType,omitempty"`
	// Uniquely identifies the resource within the collection of like resources.
	Id string `json:"Id"`
	Links Links2 `json:"Links,omitempty"`
	// This property decodes from EntryType.  If the EntryType is Event, then it is a message string.  Otherwise, it is SEL or OEM specific.  In most cases, this will be the actual Log Entry.
	Message string `json:"Message,omitempty"`
	// The values of this property shall be any arguments for the message.
	MessageArgs []string `json:"MessageArgs,omitempty"`
	// This property decodes from EntryType.  If the EntryType is Event, then it is a message id.  If the EntryType is SEL, then it contains the Event Data.  Otherwise, it is OEM specific.  This value is only used for registries - for more information, see the specification.
	MessageId string `json:"MessageId,omitempty"`
	// The name of the resource or array element.
	Name string `json:"Name"`
	Oem string `json:"Oem,omitempty"`
	// If the LogEntryCode type is OEM, this will contain the OEM-specific entry code.
	OemLogEntryCode string `json:"OemLogEntryCode,omitempty"`
	// If the EntryType is Oem, this will contain more information about the record format from the Oem.
	OemRecordFormat string `json:"OemRecordFormat,omitempty"`
	// If the Sensor Type is OEM, this will contain the OEM-specific sensor type.
	OemSensorType string `json:"OemSensorType,omitempty"`
	// This property decodes from EntryType.  If the EntryType is SEL, it is the sensor number.  If the EntryType is Event, then the count of events.  Otherwise, it is OEM specific.
	SensorNumber int32 `json:"SensorNumber,omitempty"`
	SensorType SensorType `json:"SensorType,omitempty"`
	Severity EventSeverity `json:"Severity,omitempty"`
}
