/*
 * Redfish API
 *
 * This contains the definition of a Redfish service.
 *
 * API version: 2018.3
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
type JobState string

// List of JobState
const (
	JobStateNEW JobState = "New"
	JobStateSTARTING JobState = "Starting"
	JobStateRUNNING JobState = "Running"
	JobStateSUSPENDED JobState = "Suspended"
	JobStateINTERRUPTED JobState = "Interrupted"
	JobStatePENDING JobState = "Pending"
	JobStateSTOPPING JobState = "Stopping"
	JobStateCOMPLETED JobState = "Completed"
	JobStateCANCELLED JobState = "Cancelled"
	JobStateEXCEPTION JobState = "Exception"
	JobStateSERVICE JobState = "Service"
	JobStateUSER_INTERVENTION JobState = "UserIntervention"
	JobStateCONTINUE JobState = "Continue"
)