/*
 * Redfish API
 *
 * This contains the definition of a Redfish service.
 *
 * API version: 2018.3
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// This is the interleave sets for a memory chunk.
type MemorySet struct {
	// This is the collection of memory for a particular interleave set.
	MemorySet []IdRef `json:"MemorySet,omitempty"`
	// The number of items in a collection.
	MemorySetodataCount int32 `json:"MemorySet@odata.count,omitempty"`
}
