/*
 * Redfish API
 *
 * This contains the definition of a Redfish service.
 *
 * API version: 2018.3
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// A Fibre Channel boot target configured for a network device function.
type BootTargets struct {
	// The relative priority for this entry in the boot targets array.
	BootPriority int32 `json:"BootPriority,omitempty"`
	// The Logical Unit Number (LUN) ID to boot from on the device referred to by the corresponding WWPN.
	LUNID string `json:"LUNID,omitempty"`
	// The World-Wide Port Name to boot from.
	WWPN string `json:"WWPN,omitempty"`
}
