/*
 * Redfish API
 *
 * This contains the definition of a Redfish service.
 *
 * API version: 2018.3
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
type LinkStatus2 string

// List of LinkStatus_2
const (
	LinkStatus2LINK_UP LinkStatus2 = "LinkUp"
	LinkStatus2NO_LINK LinkStatus2 = "NoLink"
	LinkStatus2LINK_DOWN LinkStatus2 = "LinkDown"
)