/*
 * Redfish API
 *
 * This contains the definition of a Redfish service.
 *
 * API version: 2018.3
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
type MemoryType string

// List of MemoryType
const (
	MemoryTypeDRAM MemoryType = "DRAM"
	MemoryTypeNVDIMM_N MemoryType = "NVDIMM_N"
	MemoryTypeNVDIMM_F MemoryType = "NVDIMM_F"
	MemoryTypeNVDIMM_P MemoryType = "NVDIMM_P"
	MemoryTypeINTEL_OPTANE MemoryType = "IntelOptane"
)