/*
 * Redfish API
 *
 * This contains the definition of a Redfish service.
 *
 * API version: 2018.3
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
type ThresholdActivation string

// List of ThresholdActivation
const (
	ThresholdActivationINCREASING ThresholdActivation = "Increasing"
	ThresholdActivationDECREASING ThresholdActivation = "Decreasing"
	ThresholdActivationEITHER ThresholdActivation = "Either"
)