/*
 * Redfish API
 *
 * This contains the definition of a Redfish service.
 *
 * API version: 2018.3
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
type StopBits string

// List of StopBits
const (
	StopBits_1 StopBits = "1"
	StopBits_2 StopBits = "2"
)