/*
 * Redfish API
 *
 * This contains the definition of a Redfish service.
 *
 * API version: 2018.3
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
type HotspareType string

// List of HotspareType
const (
	HotspareTypeNONE HotspareType = "None"
	HotspareTypeGLOBAL HotspareType = "Global"
	HotspareTypeCHASSIS HotspareType = "Chassis"
	HotspareTypeDEDICATED HotspareType = "Dedicated"
)