/*
 * Redfish API
 *
 * This contains the definition of a Redfish service.
 *
 * API version: 2018.3
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// Details of a power supplies associated with this system or device.
type PowerSupply struct {
	// The unique identifier for a resource.
	OdataId string `json:"@odata.id"`
	Actions PowerSupplyActions `json:"Actions,omitempty"`
	Assembly IdRef `json:"Assembly,omitempty"`
	// The measured efficiency of this Power Supply as a percentage.
	EfficiencyPercent float32 `json:"EfficiencyPercent,omitempty"`
	// The firmware version for this Power Supply.
	FirmwareVersion string `json:"FirmwareVersion,omitempty"`
	// Indicates if this device can be inserted or removed while the equipment is in operation.
	HotPluggable bool `json:"HotPluggable,omitempty"`
	IndicatorLED IndicatorLed2 `json:"IndicatorLED,omitempty"`
	// This is the input ranges that the power supply can use.
	InputRanges []InputRange `json:"InputRanges,omitempty"`
	// The average power output of this Power Supply.
	LastPowerOutputWatts float32 `json:"LastPowerOutputWatts,omitempty"`
	// The line input voltage at which the Power Supply is operating.
	LineInputVoltage float32 `json:"LineInputVoltage,omitempty"`
	LineInputVoltageType LineInputVoltageType `json:"LineInputVoltageType,omitempty"`
	Location Location `json:"Location,omitempty"`
	// This is the manufacturer of this power supply.
	Manufacturer string `json:"Manufacturer,omitempty"`
	// This is the identifier for the member within the collection.
	MemberId string `json:"MemberId"`
	// The model number for this Power Supply.
	Model string `json:"Model,omitempty"`
	// The name of the Power Supply.
	Name string `json:"Name,omitempty"`
	Oem string `json:"Oem,omitempty"`
	// The part number for this Power Supply.
	PartNumber string `json:"PartNumber,omitempty"`
	// The maximum capacity of this Power Supply.
	PowerCapacityWatts float32 `json:"PowerCapacityWatts,omitempty"`
	// The measured input power of this Power Supply.
	PowerInputWatts float32 `json:"PowerInputWatts,omitempty"`
	// The measured output power of this Power Supply.
	PowerOutputWatts float32 `json:"PowerOutputWatts,omitempty"`
	PowerSupplyType PowerSupplyType `json:"PowerSupplyType,omitempty"`
	// This structure is used to show redundancy for power supplies.  The Component ids will reference the members of the redundancy groups.
	Redundancy []IdRef `json:"Redundancy,omitempty"`
	// The number of items in a collection.
	RedundancyodataCount int32 `json:"Redundancy@odata.count,omitempty"`
	// The ID(s) of the resources associated with this Power Limit.
	RelatedItem []IdRef `json:"RelatedItem,omitempty"`
	// The number of items in a collection.
	RelatedItemodataCount int32 `json:"RelatedItem@odata.count,omitempty"`
	// The serial number for this Power Supply.
	SerialNumber string `json:"SerialNumber,omitempty"`
	// The spare part number for this Power Supply.
	SparePartNumber string `json:"SparePartNumber,omitempty"`
	Status Status `json:"Status,omitempty"`
}
