/*
 * Redfish API
 *
 * This contains the definition of a Redfish service.
 *
 * API version: 2018.3
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
type LineInputVoltageType string

// List of LineInputVoltageType
const (
	LineInputVoltageTypeUNKNOWN LineInputVoltageType = "Unknown"
	LineInputVoltageTypeAC_LOW_LINE LineInputVoltageType = "ACLowLine"
	LineInputVoltageTypeAC_MID_LINE LineInputVoltageType = "ACMidLine"
	LineInputVoltageTypeAC_HIGH_LINE LineInputVoltageType = "ACHighLine"
	LineInputVoltageTypeDC_NEG48_V LineInputVoltageType = "DCNeg48V"
	LineInputVoltageTypeDC380_V LineInputVoltageType = "DC380V"
	LineInputVoltageTypeAC120_V LineInputVoltageType = "AC120V"
	LineInputVoltageTypeAC240_V LineInputVoltageType = "AC240V"
	LineInputVoltageTypeAC277_V LineInputVoltageType = "AC277V"
	LineInputVoltageTypeA_CAND_DC_WIDE_RANGE LineInputVoltageType = "ACandDCWideRange"
	LineInputVoltageTypeAC_WIDE_RANGE LineInputVoltageType = "ACWideRange"
	LineInputVoltageTypeDC240_V LineInputVoltageType = "DC240V"
)