/*
 * Redfish API
 *
 * This contains the definition of a Redfish service.
 *
 * API version: 2018.3
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// The AccelerationFunction schema defines the accelerator implemented in a Processor device.
type AccelerationFunction struct {
	// The OData description of a payload.
	OdataContext string `json:"@odata.context,omitempty"`
	// The current ETag of the resource.
	OdataEtag string `json:"@odata.etag,omitempty"`
	// The unique identifier for a resource.
	OdataId string `json:"@odata.id"`
	// The type of a resource.
	OdataType string `json:"@odata.type"`
	AccelerationFunctionType AccelerationFunctionType `json:"AccelerationFunctionType,omitempty"`
	Actions Actions2 `json:"Actions,omitempty"`
	// Provides a description of this resource and is used for commonality  in the schema definitions.
	Description string `json:"Description,omitempty"`
	// An array of the reconfiguration slot identifiers for an FPGA.
	FpgaReconfigurationSlots []string `json:"FpgaReconfigurationSlots,omitempty"`
	// Uniquely identifies the resource within the collection of like resources.
	Id string `json:"Id"`
	Links Links2 `json:"Links,omitempty"`
	// The acceleration function code manufacturer.
	Manufacturer string `json:"Manufacturer,omitempty"`
	// The name of the resource or array element.
	Name string `json:"Name"`
	Oem string `json:"Oem,omitempty"`
	// The acceleration function power consumption.
	PowerWatts int32 `json:"PowerWatts,omitempty"`
	Status Status `json:"Status,omitempty"`
	UUID string `json:"UUID,omitempty"`
	// The acceleration function version.
	Version string `json:"Version,omitempty"`
}
