/*
 * Redfish API
 *
 * This contains the definition of a Redfish service.
 *
 * API version: 2018.3
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// PowerRestorePolicyTypes : The enumerations of PowerRestorePolicyTypes specify the choice of power state for the system when power is applied.
type PowerRestorePolicyTypes string

// List of PowerRestorePolicyTypes
const (
	PowerRestorePolicyTypesALWAYS_ON PowerRestorePolicyTypes = "AlwaysOn"
	PowerRestorePolicyTypesALWAYS_OFF PowerRestorePolicyTypes = "AlwaysOff"
	PowerRestorePolicyTypesLAST_STATE PowerRestorePolicyTypes = "LastState"
)