/*
 * Redfish API
 *
 * This contains the definition of a Redfish service.
 *
 * API version: 2018.3
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
type BootSourceOverrideEnabled string

// List of BootSourceOverrideEnabled
const (
	BootSourceOverrideEnabledDISABLED BootSourceOverrideEnabled = "Disabled"
	BootSourceOverrideEnabledONCE BootSourceOverrideEnabled = "Once"
	BootSourceOverrideEnabledCONTINUOUS BootSourceOverrideEnabled = "Continuous"
)