/*
 * Redfish API
 *
 * This contains the definition of a Redfish service.
 *
 * API version: 2018.3
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
type ErrorCorrection string

// List of ErrorCorrection
const (
	ErrorCorrectionNO_ECC ErrorCorrection = "NoECC"
	ErrorCorrectionSINGLE_BIT_ECC ErrorCorrection = "SingleBitECC"
	ErrorCorrectionMULTI_BIT_ECC ErrorCorrection = "MultiBitECC"
	ErrorCorrectionADDRESS_PARITY ErrorCorrection = "AddressParity"
)