/*
 * Redfish API
 *
 * This contains the definition of a Redfish service.
 *
 * API version: 2018.3
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
type ConnectorType string

// List of ConnectorType
const (
	ConnectorTypeRJ45 ConnectorType = "RJ45"
	ConnectorTypeRJ11 ConnectorType = "RJ11"
	ConnectorTypeDB9_FEMALE ConnectorType = "DB9 Female"
	ConnectorTypeDB9_MALE ConnectorType = "DB9 Male"
	ConnectorTypeDB25_FEMALE ConnectorType = "DB25 Female"
	ConnectorTypeDB25_MALE ConnectorType = "DB25 Male"
	ConnectorTypeUSB ConnectorType = "USB"
	ConnectorTypeM_USB ConnectorType = "mUSB"
	ConnectorTypeU_USB ConnectorType = "uUSB"
)