/*
 * Redfish API
 *
 * This contains the definition of a Redfish service.
 *
 * API version: 2018.3
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
type MemoryMedia string

// List of MemoryMedia
const (
	MemoryMediaDRAM MemoryMedia = "DRAM"
	MemoryMediaNAND MemoryMedia = "NAND"
	MemoryMediaINTEL3_DX_POINT MemoryMedia = "Intel3DXPoint"
	MemoryMediaPROPRIETARY MemoryMedia = "Proprietary"
)