/*
 * Redfish API
 *
 * This contains the definition of a Redfish service.
 *
 * API version: 2018.3
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
type DeviceClass string

// List of DeviceClass
const (
	DeviceClassUNCLASSIFIED_DEVICE DeviceClass = "UnclassifiedDevice"
	DeviceClassMASS_STORAGE_CONTROLLER DeviceClass = "MassStorageController"
	DeviceClassNETWORK_CONTROLLER DeviceClass = "NetworkController"
	DeviceClassDISPLAY_CONTROLLER DeviceClass = "DisplayController"
	DeviceClassMULTIMEDIA_CONTROLLER DeviceClass = "MultimediaController"
	DeviceClassMEMORY_CONTROLLER DeviceClass = "MemoryController"
	DeviceClassBRIDGE DeviceClass = "Bridge"
	DeviceClassCOMMUNICATION_CONTROLLER DeviceClass = "CommunicationController"
	DeviceClassGENERIC_SYSTEM_PERIPHERAL DeviceClass = "GenericSystemPeripheral"
	DeviceClassINPUT_DEVICE_CONTROLLER DeviceClass = "InputDeviceController"
	DeviceClassDOCKING_STATION DeviceClass = "DockingStation"
	DeviceClassPROCESSOR DeviceClass = "Processor"
	DeviceClassSERIAL_BUS_CONTROLLER DeviceClass = "SerialBusController"
	DeviceClassWIRELESS_CONTROLLER DeviceClass = "WirelessController"
	DeviceClassINTELLIGENT_CONTROLLER DeviceClass = "IntelligentController"
	DeviceClassSATELLITE_COMMUNICATIONS_CONTROLLER DeviceClass = "SatelliteCommunicationsController"
	DeviceClassENCRYPTION_CONTROLLER DeviceClass = "EncryptionController"
	DeviceClassSIGNAL_PROCESSING_CONTROLLER DeviceClass = "SignalProcessingController"
	DeviceClassPROCESSING_ACCELERATORS DeviceClass = "ProcessingAccelerators"
	DeviceClassNON_ESSENTIAL_INSTRUMENTATION DeviceClass = "NonEssentialInstrumentation"
	DeviceClassCOPROCESSOR DeviceClass = "Coprocessor"
	DeviceClassUNASSIGNED_CLASS DeviceClass = "UnassignedClass"
	DeviceClassOTHER DeviceClass = "Other"
)