/*
 * Redfish API
 *
 * This contains the definition of a Redfish service.
 *
 * API version: 2018.3
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
type MediaType2 string

// List of MediaType_2
const (
	MediaType2CD MediaType2 = "CD"
	MediaType2FLOPPY MediaType2 = "Floppy"
	MediaType2USB_STICK MediaType2 = "USBStick"
	MediaType2DVD MediaType2 = "DVD"
)