/*
 * Redfish API
 *
 * This contains the definition of a Redfish service.
 *
 * API version: 2018.3
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// This object contains properties which specify the details of the transport supported by the endpoint. The properties which are present, is dependemt on the type of transport supported by the endpoint.
type IpTransportDetails struct {
	IPv4Address IPv4Address `json:"IPv4Address,omitempty"`
	IPv6Address IPv6Address `json:"IPv6Address,omitempty"`
	// The UDP or TCP port number used by the Endpoint.
	Port float32 `json:"Port,omitempty"`
	TransportProtocol IdRef `json:"TransportProtocol,omitempty"`
}
