/*
 * Redfish API
 *
 * This contains the definition of a Redfish service.
 *
 * API version: 2018.3
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type Operation struct {
	AssociatedTask IdRef `json:"AssociatedTask,omitempty"`
	// The name of the operation.
	OperationName string `json:"OperationName,omitempty"`
	// The percentage of the operation that has been completed.
	PercentageComplete int32 `json:"PercentageComplete,omitempty"`
}
