/*
 * Redfish API
 *
 * This contains the definition of a Redfish service.
 *
 * API version: 2018.3
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
type NotifyIPv6Scope string

// List of NotifyIPv6Scope
const (
	NotifyIPv6ScopeLINK NotifyIPv6Scope = "Link"
	NotifyIPv6ScopeSITE NotifyIPv6Scope = "Site"
	NotifyIPv6ScopeORGANIZATION NotifyIPv6Scope = "Organization"
)