/*
 * Redfish API
 *
 * This contains the definition of a Redfish service.
 *
 * API version: 2018.3
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// This is the schema definition for the Metrics Service.  It represents the properties for the service itself and has links to collections of metric definitions and metric report definitions.
type TelemetryService struct {
	// The OData description of a payload.
	OdataContext string `json:"@odata.context,omitempty"`
	// The current ETag of the resource.
	OdataEtag string `json:"@odata.etag,omitempty"`
	// The unique identifier for a resource.
	OdataId string `json:"@odata.id"`
	// The type of a resource.
	OdataType string `json:"@odata.type"`
	Actions Actions2 `json:"Actions,omitempty"`
	// Provides a description of this resource and is used for commonality  in the schema definitions.
	Description string `json:"Description,omitempty"`
	// Uniquely identifies the resource within the collection of like resources.
	Id string `json:"Id"`
	LogService IdRef `json:"LogService,omitempty"`
	// The maximum number of metric reports supported by this service.
	MaxReports int32 `json:"MaxReports,omitempty"`
	MetricDefinitions IdRef `json:"MetricDefinitions,omitempty"`
	MetricReportDefinitions IdRef `json:"MetricReportDefinitions,omitempty"`
	MetricReports IdRef `json:"MetricReports,omitempty"`
	// The minimum time interval between collections supported by this service.
	MinCollectionInterval string `json:"MinCollectionInterval,omitempty"`
	// The name of the resource or array element.
	Name string `json:"Name"`
	Oem string `json:"Oem,omitempty"`
	Status Status `json:"Status,omitempty"`
	// The functions that can be performed over each metric.
	SupportedCollectionFunctions []CollectionFunction `json:"SupportedCollectionFunctions,omitempty"`
	Triggers IdRef `json:"Triggers,omitempty"`
}
