/*
 * Redfish API
 *
 * This contains the definition of a Redfish service.
 *
 * API version: 2018.3
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
type SecureBootModeType string

// List of SecureBootModeType
const (
	SecureBootModeTypeSETUP_MODE SecureBootModeType = "SetupMode"
	SecureBootModeTypeUSER_MODE SecureBootModeType = "UserMode"
	SecureBootModeTypeAUDIT_MODE SecureBootModeType = "AuditMode"
	SecureBootModeTypeDEPLOYED_MODE SecureBootModeType = "DeployedMode"
)