/*
 * Redfish API
 *
 * This contains the definition of a Redfish service.
 *
 * API version: 2018.3
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
type ReadingType string

// List of ReadingType
const (
	ReadingTypeTEMPERATURE ReadingType = "Temperature"
	ReadingTypeHUMIDITY ReadingType = "Humidity"
	ReadingTypePOWER ReadingType = "Power"
	ReadingTypeENERGYK_WH ReadingType = "EnergykWh"
	ReadingTypeENERGY_JOULES ReadingType = "EnergyJoules"
	ReadingTypeVOLTAGE ReadingType = "Voltage"
	ReadingTypeCURRENT ReadingType = "Current"
	ReadingTypeFREQUENCY ReadingType = "Frequency"
	ReadingTypePRESSURE ReadingType = "Pressure"
	ReadingTypeLIQUID_LEVEL ReadingType = "LiquidLevel"
	ReadingTypeROTATIONAL ReadingType = "Rotational"
	ReadingTypeAIR_FLOW ReadingType = "AirFlow"
	ReadingTypeLIQUID_FLOW ReadingType = "LiquidFlow"
	ReadingTypeBAROMETRIC ReadingType = "Barometric"
	ReadingTypeALTITUDE ReadingType = "Altitude"
)