/*
 * Redfish API
 *
 * This contains the definition of a Redfish service.
 *
 * API version: 2018.3
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// The VirtualMedia schema contains properties related to monitoring and control of an instance of virtual media such as a remote CD, DVD, or USB device. Virtual media functionality is provided by a Manager for a system or device.
type VirtualMedia struct {
	// The OData description of a payload.
	OdataContext string `json:"@odata.context,omitempty"`
	// The current ETag of the resource.
	OdataEtag string `json:"@odata.etag,omitempty"`
	// The unique identifier for a resource.
	OdataId string `json:"@odata.id"`
	// The type of a resource.
	OdataType string `json:"@odata.type"`
	Actions Actions2 `json:"Actions,omitempty"`
	ConnectedVia ConnectedVia `json:"ConnectedVia,omitempty"`
	// Provides a description of this resource and is used for commonality  in the schema definitions.
	Description string `json:"Description,omitempty"`
	// Uniquely identifies the resource within the collection of like resources.
	Id string `json:"Id"`
	// A URI providing the location of the selected image.
	Image string `json:"Image,omitempty"`
	// The current image name.
	ImageName string `json:"ImageName,omitempty"`
	// Indicates if virtual media is inserted in the virtual device.
	Inserted bool `json:"Inserted,omitempty"`
	// This is the media types supported as virtual media.
	MediaTypes []MediaType `json:"MediaTypes,omitempty"`
	// The name of the resource or array element.
	Name string `json:"Name"`
	Oem string `json:"Oem,omitempty"`
	// The password to be used when accessing the URI specified by the Image parameter. This property is null on a GET.
	Password string `json:"Password,omitempty"`
	TransferMethod TransferMethod `json:"TransferMethod,omitempty"`
	TransferProtocolType TransferProtocolType `json:"TransferProtocolType,omitempty"`
	// The username to be used when accessing the URI specified by the Image parameter.
	UserName string `json:"UserName,omitempty"`
	// Indicates the media is write protected.
	WriteProtected bool `json:"WriteProtected,omitempty"`
}
