/*
 * Redfish API
 *
 * This contains the definition of a Redfish service.
 *
 * API version: 2018.3
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
type SupportedEthernetCapabilities string

// List of SupportedEthernetCapabilities
const (
	SupportedEthernetCapabilitiesWAKE_ON_LAN SupportedEthernetCapabilities = "WakeOnLAN"
	SupportedEthernetCapabilitiesEEE SupportedEthernetCapabilities = "EEE"
)