/*
 * Redfish API
 *
 * This contains the definition of a Redfish service.
 *
 * API version: 2018.3
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
type PortType string

// List of PortType
const (
	PortTypeUPSTREAM_PORT PortType = "UpstreamPort"
	PortTypeDOWNSTREAM_PORT PortType = "DownstreamPort"
	PortTypeINTERSWITCH_PORT PortType = "InterswitchPort"
	PortTypeMANAGEMENT_PORT PortType = "ManagementPort"
	PortTypeBIDIRECTIONAL_PORT PortType = "BidirectionalPort"
	PortTypeUNCONFIGURED_PORT PortType = "UnconfiguredPort"
)