/*
 * Redfish API
 *
 * This contains the definition of a Redfish service.
 *
 * API version: 2018.3
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
type FlowControl string

// List of FlowControl
const (
	FlowControlNONE FlowControl = "None"
	FlowControlTX FlowControl = "TX"
	FlowControlRX FlowControl = "RX"
	FlowControlTX_RX FlowControl = "TX_RX"
)