/*
 * Redfish API
 *
 * This contains the definition of a Redfish service.
 *
 * API version: 2018.3
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// Contains references to other resources that are related to this resource.
type ControllerLinks struct {
	// An array of references to the NetworkDeviceFunctions associated with this Network Controller.
	NetworkDeviceFunctions []IdRef `json:"NetworkDeviceFunctions,omitempty"`
	// The number of items in a collection.
	NetworkDeviceFunctionsodataCount int32 `json:"NetworkDeviceFunctions@odata.count,omitempty"`
	// An array of references to the NetworkPorts associated with this Network Controller.
	NetworkPorts []IdRef `json:"NetworkPorts,omitempty"`
	// The number of items in a collection.
	NetworkPortsodataCount int32 `json:"NetworkPorts@odata.count,omitempty"`
	Oem Oem `json:"Oem,omitempty"`
	// An array of references to the PCIeDevices associated with this Network Controller.
	PCIeDevices []IdRef `json:"PCIeDevices,omitempty"`
	// The number of items in a collection.
	PCIeDevicesodataCount int32 `json:"PCIeDevices@odata.count,omitempty"`
}
