/*
 * Redfish API
 *
 * This contains the definition of a Redfish service.
 *
 * API version: 2018.3
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// KeyUsage : The usages of a key contained within a certificate.
type KeyUsage string

// List of KeyUsage
const (
	KeyUsageDIGITAL_SIGNATURE KeyUsage = "DigitalSignature"
	KeyUsageNON_REPUDIATION KeyUsage = "NonRepudiation"
	KeyUsageKEY_ENCIPHERMENT KeyUsage = "KeyEncipherment"
	KeyUsageDATA_ENCIPHERMENT KeyUsage = "DataEncipherment"
	KeyUsageKEY_AGREEMENT KeyUsage = "KeyAgreement"
	KeyUsageKEY_CERT_SIGN KeyUsage = "KeyCertSign"
	KeyUsageCRL_SIGNING KeyUsage = "CRLSigning"
	KeyUsageENCIPHER_ONLY KeyUsage = "EncipherOnly"
	KeyUsageDECIPHER_ONLY KeyUsage = "DecipherOnly"
	KeyUsageSERVER_AUTHENTICATION KeyUsage = "ServerAuthentication"
	KeyUsageCLIENT_AUTHENTICATION KeyUsage = "ClientAuthentication"
	KeyUsageCODE_SIGNING KeyUsage = "CodeSigning"
	KeyUsageEMAIL_PROTECTION KeyUsage = "EmailProtection"
	KeyUsageTIMESTAMPING KeyUsage = "Timestamping"
	KeyUsageOCSP_SIGNING KeyUsage = "OCSPSigning"
)