/*
 * Redfish API
 *
 * This contains the definition of a Redfish service.
 *
 * API version: 2018.3
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// This is the schema definition for the Endpoint resource. It represents the properties of an entity that sends or receives protocol defined messages over a transport.
type Endpoint struct {
	// The OData description of a payload.
	OdataContext string `json:"@odata.context,omitempty"`
	// The current ETag of the resource.
	OdataEtag string `json:"@odata.etag,omitempty"`
	// The unique identifier for a resource.
	OdataId string `json:"@odata.id"`
	// The type of a resource.
	OdataType string `json:"@odata.type"`
	Actions Actions2 `json:"Actions,omitempty"`
	// All the entities connected to this endpoint.
	ConnectedEntities []ConnectedEntity `json:"ConnectedEntities,omitempty"`
	// Provides a description of this resource and is used for commonality  in the schema definitions.
	Description string `json:"Description,omitempty"`
	EndpointProtocol IdRef `json:"EndpointProtocol,omitempty"`
	// The amount of memory in Bytes that the Host should allocate to connect to this endpoint.
	HostReservationMemoryBytes int32 `json:"HostReservationMemoryBytes,omitempty"`
	// This array contains details for each IP transport supported by this endpoint. The array structure can be used to model multiple IP addresses for this endpoint.
	IPTransportDetails []IpTransportDetails `json:"IPTransportDetails,omitempty"`
	// Uniquely identifies the resource within the collection of like resources.
	Id string `json:"Id"`
	// Identifiers for this endpoint.
	Identifiers []Identifier2 `json:"Identifiers,omitempty"`
	Links Links2 `json:"Links,omitempty"`
	// The name of the resource or array element.
	Name string `json:"Name"`
	Oem string `json:"Oem,omitempty"`
	PciId PciId `json:"PciId,omitempty"`
	// Redundancy information for the lower level endpoints supporting this endpoint.
	Redundancy []IdRef `json:"Redundancy,omitempty"`
	// The number of items in a collection.
	RedundancyodataCount int32 `json:"Redundancy@odata.count,omitempty"`
	Status Status `json:"Status,omitempty"`
}
