/*
 * Redfish API
 *
 * This contains the definition of a Redfish service.
 *
 * API version: 2018.3
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
type ReadingUnits string

// List of ReadingUnits
const (
	ReadingUnitsRPM ReadingUnits = "RPM"
	ReadingUnitsPERCENT ReadingUnits = "Percent"
)