/*
 * Redfish API
 *
 * This contains the definition of a Redfish service.
 *
 * API version: 2018.3
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
type BootSource string

// List of BootSource
const (
	BootSourceNONE BootSource = "None"
	BootSourcePXE BootSource = "Pxe"
	BootSourceFLOPPY BootSource = "Floppy"
	BootSourceCD BootSource = "Cd"
	BootSourceUSB BootSource = "Usb"
	BootSourceHDD BootSource = "Hdd"
	BootSourceBIOS_SETUP BootSource = "BiosSetup"
	BootSourceUTILITIES BootSource = "Utilities"
	BootSourceDIAGS BootSource = "Diags"
	BootSourceUEFI_SHELL BootSource = "UefiShell"
	BootSourceUEFI_TARGET BootSource = "UefiTarget"
	BootSourceSD_CARD BootSource = "SDCard"
	BootSourceUEFI_HTTP BootSource = "UefiHttp"
	BootSourceREMOTE_DRIVE BootSource = "RemoteDrive"
	BootSourceUEFI_BOOT_NEXT BootSource = "UefiBootNext"
)