/*
 * Redfish API
 *
 * This contains the definition of a Redfish service.
 *
 * API version: 2018.3
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// This object contains settings for software update via HttpPushUri.
type HttpPushUriOptions struct {
	HttpPushUriApplyTime HttpPushUriApplyTime `json:"HttpPushUriApplyTime,omitempty"`
}
