/*
 * Redfish API
 *
 * This contains the definition of a Redfish service.
 *
 * API version: 2018.3
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// Contains an error payload from a Redfish Service.
type RedfishError struct {
	Error RedfishErrorError `json:"error"`
}
