/*
 * Redfish API
 *
 * This contains the definition of a Redfish service.
 *
 * API version: 2018.3
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
type EncryptionTypes string

// List of EncryptionTypes
const (
	EncryptionTypesNATIVE_DRIVE_ENCRYPTION EncryptionTypes = "NativeDriveEncryption"
	EncryptionTypesCONTROLLER_ASSISTED EncryptionTypes = "ControllerAssisted"
	EncryptionTypesSOFTWARE_ASSISTED EncryptionTypes = "SoftwareAssisted"
)