/*
 * Redfish API
 *
 * This contains the definition of a Redfish service.
 *
 * API version: 2018.3
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// This action is used to reset statistics related to this sensor.
type ResetStatisticsRequestBody struct {
}
