/*
 * Redfish API
 *
 * This contains the definition of a Redfish service.
 *
 * API version: 2018.3
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// This type contains security capabilities of a Memory entity.
type SecurityCapabilities struct {
	// Support for locking the configuration.
	ConfigurationLockCapable bool `json:"ConfigurationLockCapable,omitempty"`
	// Support for data locking.
	DataLockCapable bool `json:"DataLockCapable,omitempty"`
	// Maximum number of passphrases supported for this Memory.
	MaxPassphraseCount int32 `json:"MaxPassphraseCount,omitempty"`
	// Memory passphrase set capability.
	PassphraseCapable bool `json:"PassphraseCapable,omitempty"`
	// Maximum number of incorrect passphrase attempts allowed before memory is locked.
	PassphraseLockLimit int32 `json:"PassphraseLockLimit,omitempty"`
	// Security states supported by the Memory.
	SecurityStates []SecurityStates `json:"SecurityStates,omitempty"`
}
