/*
 * Redfish API
 *
 * This contains the definition of a Redfish service.
 *
 * API version: 2018.3
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type Voltage struct {
	// The unique identifier for a resource.
	OdataId string `json:"@odata.id"`
	Actions VoltageActions `json:"Actions,omitempty"`
	// Below normal range but not yet fatal.
	LowerThresholdCritical float32 `json:"LowerThresholdCritical,omitempty"`
	// Below normal range and is fatal.
	LowerThresholdFatal float32 `json:"LowerThresholdFatal,omitempty"`
	// Below normal range.
	LowerThresholdNonCritical float32 `json:"LowerThresholdNonCritical,omitempty"`
	// Maximum value for this Voltage sensor.
	MaxReadingRange float32 `json:"MaxReadingRange,omitempty"`
	// This is the identifier for the member within the collection.
	MemberId string `json:"MemberId"`
	// Minimum value for this Voltage sensor.
	MinReadingRange float32 `json:"MinReadingRange,omitempty"`
	// Voltage sensor name.
	Name string `json:"Name,omitempty"`
	Oem Oem `json:"Oem,omitempty"`
	PhysicalContext IdRef `json:"PhysicalContext,omitempty"`
	// The present reading of the voltage sensor.
	ReadingVolts float32 `json:"ReadingVolts,omitempty"`
	// Describes the areas or devices to which this voltage measurement applies.
	RelatedItem []IdRef `json:"RelatedItem,omitempty"`
	// The number of items in a collection.
	RelatedItemodataCount int32 `json:"RelatedItem@odata.count,omitempty"`
	// A numerical identifier to represent the voltage sensor.
	SensorNumber int32 `json:"SensorNumber,omitempty"`
	Status Status `json:"Status,omitempty"`
	// Above normal range but not yet fatal.
	UpperThresholdCritical float32 `json:"UpperThresholdCritical,omitempty"`
	// Above normal range and is fatal.
	UpperThresholdFatal float32 `json:"UpperThresholdFatal,omitempty"`
	// Above normal range.
	UpperThresholdNonCritical float32 `json:"UpperThresholdNonCritical,omitempty"`
}
