/*
 * Redfish API
 *
 * This contains the definition of a Redfish service.
 *
 * API version: 2018.3
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// This object describes the memory of the system in general detail.
type MemorySummary struct {
	MemoryMirroring MemoryMirroring `json:"MemoryMirroring,omitempty"`
	Status Status `json:"Status,omitempty"`
	// The total configured operating system-accessible memory (RAM), measured in GiB.
	TotalSystemMemoryGiB float32 `json:"TotalSystemMemoryGiB,omitempty"`
	// The total configured, system-accessible persistent memory, measured in GiB.
	TotalSystemPersistentMemoryGiB float32 `json:"TotalSystemPersistentMemoryGiB,omitempty"`
}
