/*
 * Redfish API
 *
 * This contains the definition of a Redfish service.
 *
 * API version: 2018.3
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
type TransferProtocolType string

// List of TransferProtocolType
const (
	TransferProtocolTypeCIFS TransferProtocolType = "CIFS"
	TransferProtocolTypeFTP TransferProtocolType = "FTP"
	TransferProtocolTypeSFTP TransferProtocolType = "SFTP"
	TransferProtocolTypeHTTP TransferProtocolType = "HTTP"
	TransferProtocolTypeHTTPS TransferProtocolType = "HTTPS"
	TransferProtocolTypeNFS TransferProtocolType = "NFS"
	TransferProtocolTypeSCP TransferProtocolType = "SCP"
	TransferProtocolTypeTFTP TransferProtocolType = "TFTP"
	TransferProtocolTypeOEM TransferProtocolType = "OEM"
)