/*
 * Redfish API
 *
 * This contains the definition of a Redfish service.
 *
 * API version: 2018.3
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
type FpgaInterfaceType string

// List of FpgaInterfaceType
const (
	FpgaInterfaceTypeQPI FpgaInterfaceType = "QPI"
	FpgaInterfaceTypeUPI FpgaInterfaceType = "UPI"
	FpgaInterfaceTypePC_IE FpgaInterfaceType = "PCIe"
	FpgaInterfaceTypeETHERNET FpgaInterfaceType = "Ethernet"
	FpgaInterfaceTypeOEM FpgaInterfaceType = "OEM"
)