/*
 * Redfish API
 *
 * This contains the definition of a Redfish service.
 *
 * API version: 2018.3
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// The self-described link capabilities of an assocaited port.
type SupportedLinkCapabilities struct {
	// Indicates whether the port has the capability to auto negotiate speed.
	AutoSpeedNegotiation bool `json:"AutoSpeedNegotiation,omitempty"`
	// The self-described link network speed capabilities of this port. Note: Should this be a new enumerated type of link speeds?.
	CapableLinkSpeedMbps []int32 `json:"CapableLinkSpeedMbps,omitempty"`
	LinkNetworkTechnology LinkNetworkTechnology `json:"LinkNetworkTechnology,omitempty"`
	// The speed of the link in Mbps when this link network technology is active.
	LinkSpeedMbps int32 `json:"LinkSpeedMbps,omitempty"`
}
