/*
 * Redfish API
 *
 * This contains the definition of a Redfish service.
 *
 * API version: 2018.3
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// The response body for the GenerateCSR action.
type GenerateCsrResponse struct {
	// The string for the certificate signing request.
	CSRString string `json:"CSRString"`
	CertificateCollection IdRef `json:"CertificateCollection"`
}
