/*
 * Redfish API
 *
 * This contains the definition of a Redfish service.
 *
 * API version: 2018.3
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// This type describes the Identification information for a processor.
type ProcessorId struct {
	// The effective Family for this processor.
	EffectiveFamily string `json:"EffectiveFamily,omitempty"`
	// The effective Model for this processor.
	EffectiveModel string `json:"EffectiveModel,omitempty"`
	// The contents of the Identification Registers (CPUID) for this processor.
	IdentificationRegisters string `json:"IdentificationRegisters,omitempty"`
	// The Microcode Information for this processor.
	MicrocodeInfo string `json:"MicrocodeInfo,omitempty"`
	// The Step value for this processor.
	Step string `json:"Step,omitempty"`
	// The Vendor Identification for this processor.
	VendorId string `json:"VendorId,omitempty"`
}
