/*
 * Redfish API
 *
 * This contains the definition of a Redfish service.
 *
 * API version: 2018.3
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
type AddressRangeType string

// List of AddressRangeType
const (
	AddressRangeTypeVOLATILE AddressRangeType = "Volatile"
	AddressRangeTypePMEM AddressRangeType = "PMEM"
	AddressRangeTypeBLOCK AddressRangeType = "Block"
)