/*
 * Redfish API
 *
 * This contains the definition of a Redfish service.
 *
 * API version: 2018.3
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// The value of the HTTP header is the property value.  The header name is the property name.
type HttpHeaderProperty struct {
}
