/*
 * Redfish API
 *
 * This contains the definition of a Redfish service.
 *
 * API version: 2018.3
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// This type describes the memory directly attached or integrated within a processor.
type ProcessorMemory struct {
	// The memory capacity in MiB.
	CapacityMiB int32 `json:"CapacityMiB,omitempty"`
	// This indicates whether this memory is integrated within the Processor.
	IntegratedMemory bool `json:"IntegratedMemory,omitempty"`
	MemoryType ProcessorMemoryType `json:"MemoryType,omitempty"`
	// The operating speed of the memory in MHz.
	SpeedMHz int32 `json:"SpeedMHz,omitempty"`
}
