/*
 * Redfish API
 *
 * This contains the definition of a Redfish service.
 *
 * API version: 2018.3
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// Port contains properties describing a port of a switch.
type Port struct {
	// The OData description of a payload.
	OdataContext string `json:"@odata.context,omitempty"`
	// The current ETag of the resource.
	OdataEtag string `json:"@odata.etag,omitempty"`
	// The unique identifier for a resource.
	OdataId string `json:"@odata.id"`
	// The type of a resource.
	OdataType string `json:"@odata.type"`
	Actions Actions2 `json:"Actions,omitempty"`
	// The current speed of this port.
	CurrentSpeedGbps float32 `json:"CurrentSpeedGbps,omitempty"`
	// Provides a description of this resource and is used for commonality  in the schema definitions.
	Description string `json:"Description,omitempty"`
	// Uniquely identifies the resource within the collection of like resources.
	Id string `json:"Id"`
	Links Links2 `json:"Links,omitempty"`
	Location Location `json:"Location,omitempty"`
	// The maximum speed of this port as currently configured.
	MaxSpeedGbps float32 `json:"MaxSpeedGbps,omitempty"`
	// The name of the resource or array element.
	Name string `json:"Name"`
	Oem Oem `json:"Oem,omitempty"`
	// This is the label of this port on the physical switch package.
	PortId string `json:"PortId,omitempty"`
	PortProtocol IdRef `json:"PortProtocol,omitempty"`
	PortType PortType `json:"PortType,omitempty"`
	Status Status `json:"Status,omitempty"`
	// The number of lanes, phys, or other physical transport links that this port contains.
	Width int32 `json:"Width,omitempty"`
}
