/*
 * Redfish API
 *
 * This contains the definition of a Redfish service.
 *
 * API version: 2018.3
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// The set of thresholds defined for a sensor.
type Thresholds struct {
	LowerCaution Threshold `json:"LowerCaution,omitempty"`
	LowerCritical Threshold `json:"LowerCritical,omitempty"`
	LowerFatal Threshold `json:"LowerFatal,omitempty"`
	UpperCaution Threshold `json:"UpperCaution,omitempty"`
	UpperCritical Threshold `json:"UpperCritical,omitempty"`
	UpperFatal Threshold `json:"UpperFatal,omitempty"`
}
