/*
 * Redfish API
 *
 * This contains the definition of a Redfish service.
 *
 * API version: 2018.3
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
import (
	"time"
)

// This object contains settings for when software is to be applied when provided via HttpPushUri.
type HttpPushUriApplyTime struct {
	ApplyTime ApplyTime `json:"ApplyTime,omitempty"`
	// The value of this property as specified by client indicates the expiry time of maintenance window in seconds.
	MaintenanceWindowDurationInSeconds int32 `json:"MaintenanceWindowDurationInSeconds,omitempty"`
	// The value of this property as specified by client to indicate the start time of a maintenance window.
	MaintenanceWindowStartTime time.Time `json:"MaintenanceWindowStartTime,omitempty"`
}
